### ISSUE TITLE
AiService throw a ClassNotFoundException outside of a request scope

### ISSUE THREAD

**Issue by anis-gha** [quarkiverse/quarkus-langchain4j#1012]
## Description
Hello, I'm working on a project using **Quarkus** + **Kotlin** + **Langchain4j** with a queue system that uses **Kotlin Coroutine** to call specific quarkus services to handle specific task.
I'm taking advantage of Kotlin Coroutine to allow multiple task being run when limiting the number of total executions.
_(i've provided a basic representation of the system in **Steps to Reproduce** section)_

The issue here, is when calling the service that handle the task which has a AiService as a dependency, i get a `java.lang.ClassNotFoundException` when calling this AiService.
The service can only be used inside a request scope level while i've added the @ApplicationScoped annontation on the AiService.

The exact stacktrace is : https://pastebin.com/5A5aQniX

## Expected Behavior

Being able to use the AiService outside of a request scope when using the @ApplicationScope annontation on the AiService.

## Current Behavior

The service only working on a request scope level, outside we get a ClassNotFoundException.

## Solution

?

## Steps to Reproduce

1. Git clone : https://github.com/anis-gha/quarkus-kotlin-coroutine-langchain-bug
2. Run quarkusDev (no api key needed since it's doesn't not work)
3. Call http://localhost:8080/api/ (curl -X GET -v http://localhost:8080/api/)

### Thank you for your help !

**Comment by geoand** [comment]
Thanks for the great report description and the reproducer.

I'll have a look in a few days

**Comment by geoand** [comment]
This has to do with the fact that when Coroutines are launched, the Thread Context ClassLoader is not set properly.

Using the following diff, things start to work as expected:

```diff
diff --git a/src/main/kotlin/gg/anis/api/ApiService.kt b/src/main/kotlin/gg/anis/api/ApiService.kt
index e8bdecf..cf2e4ff 100644
--- a/src/main/kotlin/gg/anis/api/ApiService.kt
+++ b/src/main/kotlin/gg/anis/api/ApiService.kt
@@ -38,7 +38,9 @@ class ApiService(
 
     @Startup
     open fun startup() {
+        val originalTCCL = Thread.currentThread().contextClassLoader
         launch {
+            Thread.currentThread().contextClassLoader = originalTCCL
             processQueue()
         }
     }
@@ -63,7 +65,9 @@ class ApiService(
                 delay(100)
             }
 
+            val originalTCCL = Thread.currentThread().contextClassLoader
             launch {
+                Thread.currentThread().contextClassLoader = originalTCCL
                 try {
                     activeScans.add(queuedScan.id)
                     processScan(queuedScan)
@@ -82,8 +86,9 @@ class ApiService(
         try {
             val service = scanServices.firstOrNull { it.canHandle(queuedScan) }
                 ?: throw Exception("No suitable service found for scan ${queuedScan.id}")
-
+            val originalTCCL = Thread.currentThread().contextClassLoader
             val result = withTimeout(1.minutes.inWholeMilliseconds) {
+                Thread.currentThread().contextClassLoader = originalTCCL
                 service.processScan(queuedScan)
             }
 
@@ -103,4 +108,4 @@ interface ScanService {
 
 data class Scan(
     val id: UUID
-)
\ No newline at end of file
+)
diff --git a/src/main/resources/application.properties b/src/main/resources/application.properties
index f0d3d48..538b75b 100644
--- a/src/main/resources/application.properties
+++ b/src/main/resources/application.properties
@@ -3,4 +3,6 @@ quarkus.langchain4j.openai.log-requests=true
 quarkus.langchain4j.openai.log-responses=true
 quarkus.langchain4j.openai.chat-model.model-name=chatgpt-4o-latest
 quarkus.langchain4j.openai.timeout=60
-quarkus.langchain4j.chat-model.provider=openai
\ No newline at end of file
+quarkus.langchain4j.chat-model.provider=openai
+
+quarkus.package.jar.decompiler.enabled=true
```
