### ISSUE TITLE
Missing quarkus-langchain4j-*.adoc files

### ISSUE THREAD

**Issue by andreadimaio** [quarkiverse/quarkus-langchain4j#1016]
The `quarkus-langchain4j-*.adoc` files, which contain configurations for each provider, are not automatically generated after running the `mvn clean install` command. Despite attempting various configuration adjustments for different providers within the workspace, none of the expected `quarkus-langchain4j-*.adoc` files are produced in the output directory.

**Comment by geoand** [comment]
@gsmet any ideas on this one?

**Comment by gsmet** [comment]
Yes, let me fix that for you.

**Comment by geoand** [comment]
🙏

**Comment by gsmet** [comment]
See https://github.com/quarkiverse/quarkus-langchain4j/pull/1017 .
