### ISSUE TITLE
OutputGuardrails not permitting override generated output

### ISSUE THREAD

**Issue by lordofthejars** [quarkiverse/quarkus-langchain4j#1020]
OutputGuardrails are great for validating that the output is valid, such as whether it is in JSON format or follows any schema.

The problem is that sometimes LLMs, even though we explicitly say, return only a JSON document and nothing else, it returns more info. For example:

{ name: "Alex", age: 18 } ```

You see, that might append at the end of the JSON the snippet characters.
We found this today with @mariofusco, so we said we don't need another call to LLM; we can just sanitize the output easily and quickly.

```
@Override
    public OutputGuardrailResult validate(AiMessage responseFromLLM) {
        String llmResponse = responseFromLLM.text();
        logger.infof("LLM output: %s", llmResponse);

        if (validateJson(llmResponse)) {
            return success();
        }
       
        String json = trimNonJson(llmResponse);

        if (validateJson(json)) {
            return successWith(json); <<<<<<<<<<<<
        }

        return reprompt("Invalid JSON",
            "Make sure you return a valid JSON object following "
                + "the specified format");
    }
```

The problem is that the output guard doesn't allow the result to be overridden.

**Comment by mariofusco** [comment]
I believe this is something that also @gsmet noted and requested a few weeks ago. Please feel free to assign this issue to me, I'm already at work on it. /cc @geoand

**Comment by mariofusco** [comment]
My [pull request](https://github.com/quarkiverse/quarkus-langchain4j/pull/1021) has been merged, I think this issue can be closed.

**Comment by geoand** [comment]
Good point!
