### ISSUE TITLE
Infinispan as embedding storage support

### ISSUE THREAD

**Issue by karesti** [quarkiverse/quarkus-langchain4j#103]
Infinispan is implementing the Vector Search capabilities. 
Tagging the issue here

**Comment by geoand** [comment]
@karesti I am sure what your timeline for this is, but I just wanted to let you know that this extension releases much quicker than the uptream langchain4j project.

**Comment by karesti** [comment]
@geoand we need 15.0.0.Final version in the infinispan-client upstream quarkus as well

**Comment by karesti** [comment]
@geoand somewhere in january will be releasing 15.0.0.Final, then with the latest quarkus release containing the version, we can integrate all here. for now i'm working locally with snapshot and dev versions to fill all the gaps for the integration in langchain upstream and here

**Comment by geoand** [comment]
Sounds good
