### ISSUE TITLE
Generic ModelAuthProviders should work with named models

### ISSUE THREAD

**Issue by sberyozkin** [quarkiverse/quarkus-langchain4j#1038]
While working on #733, I've found that a generic `ModelAuthProvider` such as the one provided by `quarkus-langchain4j-oidc-model-auth-provider` does not work with the `azure-openai` chat model provider, because the model name is set to `openai` and it leads to `ModelAuthProvider.resolve` finding no matching `ModelAuthProvider`.

The current `ModelAuthProvider.resolve` logic is as follows:
* If the model name is not null - then check only `ModelAuthProvider` annotated with a matching `@ModelName` qualifier
* Otherwise, if the model name is null, `ModelAuthProvider` without the qualifier is collected

The problem is that `ModelAuthProvider` provided by `quarkus-langchain4j-oidc-model-auth-provider` does not know in advance any model names, all it can do is to propagate either the incoming bearer access token or the current authorization code flow access token, representing the user authentication. 

I've done a workaround in #733, but it will most likely need to be reworked... 

I have the following suggestion:
* `ModelAuthProvider` has a new method added, say `modelNames`, default implementation will return an empty set
* `quarkus-langchain4j-oidc-model-auth-provider` runtime configuration will have a `supported-models` Set property which will be returned from the OIDC  `ModelAuthProvider` provided by this extension
* `ModelAuthProvider.resolve`: if the model name is not null, it will check `@ModelName` qualifiers, then, if no matching `ModelAuthProvider` is found, it will check `ModelAuthProvider` without qualifiers and will check `modelNames` method...

I'm not 100% happy with this suggestion, but I'm not sure what else can be done...

Or, perhaps the simplest solution can be the workaround I did in #733 ? If the model name is not null - check the one with the matching qualifier, if none is found, why don't pick up a generic one ? 
It seems the decision about which model a given `ModelAuthProvider` wants to work with should be coming from the `ModelAuthProvider` ?

@csotiriou @geoand, what do you think ? I'll be happy to work on the PR once the solution is agreed upon

Thanks

**Comment by geoand** [comment]
@sberyozkin do you have examples of what you did to handle the situation?

**Comment by sberyozkin** [comment]
Hi @geoand 

Do you mean what exactly did I do to workaround the current constraint ? See [this update](https://github.com/quarkiverse/quarkus-langchain4j/pull/733/files#diff-cb842e3d80847edc84e6533234e36388939746893ea515a4601e5dfe2ee30d8f):

* If the model name is not null - check a matching `@ModelName` qualified `ModelAuthProvider` first
* If no matching ModelAuthProvider is found in the previous step then get a generic `ModelAuthProvider` provider

That seems correct...

As far as the current demo configuration is concerned, it is [here](https://github.com/quarkiverse/quarkus-langchain4j/pull/733/files#diff-4cc3eb37b9efad29dc901705aa99e5e9e61cacd6f3153fdcbbd64cbd3d6393c5) - 2 chat models are declared, but it does not feel right that making the model named somewhere in the config will  disable a generic `ModelAuthProvider`...

**Comment by geoand** [comment]
Hm..

The way I see it, something like:

```java
    @Singleton
    public static class OllamaClientAuthHeaderFilter implements ModelAuthProvider {

        @Override
        public String getAuthorization(Input input) {
            return "Bearer test";
        }
    }
```

applies to `quarkus.langchain4j.ollama.base-url=http://localhost:8080` 

while:

```java
    @Singleton
    @ModelName("foo") 
    public static class NamedOllamaClientAuthHeaderFilter implements ModelAuthProvider {

        @Override
        public String getAuthorization(Input input) {
            return "Bearer test2";
        }
    }
```

applies to `quarkus.langchain4j.ollama.foo.base-url=http://localhost:9090`

**Comment by sberyozkin** [comment]
@geoand 

>As far as the current demo configuration is concerned, it is [here](https://github.com/quarkiverse/quarkus-langchain4j/pull/733/files#diff-4cc3eb37b9efad29dc901705aa99e5e9e61cacd6f3153fdcbbd64cbd3d6393c5) - 2 chat models are declared, but it does not feel right that making the model named somewhere in the config will disable a generic ModelAuthProvider...

Right, [here](https://github.com/quarkiverse/quarkus-langchain4j/pull/733/files#diff-4cc3eb37b9efad29dc901705aa99e5e9e61cacd6f3153fdcbbd64cbd3d6393c5R30), the Azure OpenAI model is named, because the Vertex Gemini is a default one - that is, I did not name the Azure OpenAI model `openai` because I meant to have it only matched by `@ModelName("openai") MyModelAuthProvider` - but because the demo needs to support more than one model.

FYI, the last time I tested it did work for  Vertex Gemini in this setup because the model is not named. I'm pretty sure that if I keep only the Azure OpenAI model and make it unnamed/default, it will be fine as well...

**Comment by sberyozkin** [comment]
@geoand Right, I think this is how it works on `main` - but it makes it impossible to apply `quarkus-langchain4j-oidc-model-auth-provider` to named models

**Comment by geoand** [comment]
@sberyozkin How so? My example shows exactly that, no?

**Comment by sberyozkin** [comment]
Hmm, may be I'm missing something... So how would I apply the OIDC `ModelAuthProvider` that is shipped with `quarkus-langchain4j` to `quarkus.langchain4j.ollama.foo.base-url=http://localhost:9090` ?

**Comment by geoand** [comment]
Ah okay, now I see what you are talking about.

**Comment by sberyozkin** [comment]
Yeah, thanks, I guess it should be the other way around, the named `ModelAuthProvider` can only match the named model, while generic/anonymous ones can be applicable to any model.
I can propose the code I did in my draft PR as a separate enhancement, unless @csotiriou  or yourself will have some reservations...

**Comment by geoand** [comment]
I guess we will have to go with your porposed solution

**Comment by sberyozkin** [comment]
Sure, I'll wait for one day for more comments and then open a PR asking yourself and @csotiriou to review in any case, cheers

**Comment by geoand** [comment]
👍🏽
