### ISSUE TITLE
Bump to Jlama 0.8.1

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#1040]
@mariofusco are you interested in bumping the Jlama extension to the latest version of Jlama that includes your changes there?

**Comment by mariofusco** [comment]
Yes please, I want to experiment with Granite models integration this week. I was about the send a pull request right now actually, let me know if I should do it or you can take care of the bump.

**Comment by geoand** [comment]
Go right ahead!

**Comment by mariofusco** [comment]
@geoand feel free to close this.
