### ISSUE TITLE
False warning on Ollama model names

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#1043]
After [the](https://github.com/quarkiverse/quarkus-langchain4j/pull/911) we now get:

```
[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.langchain4j.ollama.embedding-model.model-name" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.langchain4j.ollama.chat-model.model-name" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
``` 

when the application starts.

@radcortez any idea what the issue is?

**Comment by radcortez** [comment]
Yes. I've noticed that you added both a fallback and a relocate, but they both use the same function, when the function should be inverse.

The fallback and the relocation add the resolved property to the list of names (used to determine which properties are unused). You get the warning if the unmapped property does not cycle back to the mapped property. For instance `foo` fallbacks to `bar` which relocates to `foo`.

**Comment by geoand** [comment]
Oh, I didn't realize that, thanks for spotting the problem!
