### ISSUE TITLE
Migrate to the `JsonSchemaElement` API

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-langchain4j#1054]
When defining tools, use the new `JsonSchemaElement` API instead of `JsonSchemaProperty`.

See https://github.com/quarkiverse/quarkus-langchain4j/issues/1036#issuecomment-2457557006 for some details. This needs to be put on hold a bit until the next upstream LangChain4j release, as it contains some things that are needed.

**Comment by edeandrea** [comment]
I've already started work on this and have some things stashed, so once the next LangChain4j release is out and taken by the extension then I can complete this work.

**Comment by geoand** [comment]
🙏🏽

**Comment by edeandrea** [comment]
I will take this up now that #1075 has been done.

**Comment by geoand** [comment]
Now is the time :)

**Comment by edeandrea** [comment]
I'll try to get to this next week

**Comment by geoand** [comment]
🙏🏽
