### ISSUE TITLE
Enable resolution of AI services by EL name

### ISSUE THREAD

**Issue by aldettinger** [quarkiverse/quarkus-langchain4j#1087]
Enabling AI services bean resolution by EL name may improve user experience in Apache Camel.

Like we could define an AI service like below:
```
@RegisterAiService
@ApplicationScoped
@Named("customPojoExtractionService")
public interface CustomPojoExtractionService {...}
```
And then use it from a Camel route like that:
```
from("...").bean("customPojoExtractionService");
// Under the hood, camel uses jakarta.enterprise.inject.spi.BeanManager.getBeans("customPojoExtractionService");
```

One way to implement could be to copy the `@Named` annotation value when quarkus-langchain4j generates the AI service implementation.

Does it sound a valid idea to start working on a pr ?
I guess it is valid to assume that there will forever be only a single AI service implementation class per AI service interface ?
Maybe later on, it makes sense to also implement resolution by interface type ? and by @Identifier ?

**Comment by geoand** [comment]
We generally try to avoid named beans as much as possible. 

In the specific case of AiService, why use the name of the bean and not the type?

**Comment by aldettinger** [comment]
Along the years, it's common habit for camel users to reference beans by name and to a less extent by type. 
In the specific case of AiService, there is camel bug or maybe limitations preventing the resolution by interface.
This could be investigated for sure but that's actually another topic.

Back to resolution by name, if we consider it's a bad design in the specific case of AiService, then maybe we prefer to close this ticket ? What do you think ?

**Comment by geoand** [comment]
If you want to add opt-in support for `@Named` like you propose, that's fine - we can have it

**Comment by aldettinger** [comment]
It could be worth exploring, just need a bit more info about opt-in support.
How is opt-in usually implemented ? Maybe we have an example somewhere please ?

**Comment by geoand** [comment]
I don't have any examples, but in this case we likely just need to read the annotation and pass the value to `ExtendedBeanConfigurator`.

https://github.com/quarkiverse/quarkus-langchain4j/blob/bc7d6c05f942f94de0cd052292b0e3d456ab4f16/core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java#L469 is where the bean is built, so if you include (an optional) bean name in `DeclarativeAiServiceBuildItem`, then you can pass it to the bean creation process.

**Comment by aldettinger** [comment]
Hi @geoand, I wonder if the fix is right actually. Looking at the resolved bean, the class is as below:

```
bean.getClass(): class 
 io.quarkiverse.langchain4j.runtime.aiservice.QuarkusAiServiceContext_nmRnTiIZjJtT8bkUHQ3Y8a_fkKY_Synthetic_Bean
bean.getBeanClass(): class io.quarkiverse.langchain4j.runtime.aiservice.QuarkusAiServiceContext
```

However, we should have an instance of the registered service, shouldn't we ?

**Comment by geoand** [comment]
If you use `ClientProxy.unwrap(bean).getClass()` you should see the expected value

**Comment by aldettinger** [comment]
So I have this:

```
******* bean.getClass(): class io.quarkiverse.langchain4j.runtime.aiservice.QuarkusAiServiceContext_nmRnTiIZjJtT8bkUHQ3Y8a_fkKY_Synthetic_Bean
******* bean.getBeanClass(): class io.quarkiverse.langchain4j.runtime.aiservice.QuarkusAiServiceContext
******* ClientProxy.unwrap(bean).getClass(): class io.quarkiverse.langchain4j.runtime.aiservice.QuarkusAiServiceContext_nmRnTiIZjJtT8bkUHQ3Y8a_fkKY_Synthetic_Bean
******* ClientProxy.unwrap(bean).getName(): myNamedServiceBean
******* ClientProxy.unwrap(bean).getInjectionPoints(): []
```

Does it sound right ?

**Comment by geoand** [comment]
It should be

**Comment by aldettinger** [comment]
Hello @geoand, the AI service annotated with `@Named("aiServiceResolvedByName") ` is still unresolved in Camel.

As far as I can debug, when invoking `manager.getBeans("aiServiceResolvedByName")`, it returns `[SYNTHETIC bean [class=io.quarkiverse.langchain4j.runtime.aiservice.QuarkusAiServiceContext, id=TYpRs3KmsFjdSvyqkIN1qVZuAoI]]`.

Shouldn't it return `org.apache.camel.quarkus.component.langchain.it.AiServiceResolvedByName$$QuarkusImpl` instead ?

Not that there is such a `QuarkusImpl` instance when debugging `ArcContainerImpl.getMatchingBeans("aiServiceResolvedByName")` however, it's not matching by name [here](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ArcContainerImpl.java#L850).

Does it make any sense ?

**Comment by geoand** [comment]
> Does it make any sense ?

I would need to see an example really :)

**Comment by aldettinger** [comment]
Hi @geoand, many thanks for patience. Having a full fledged example would imply waiting for a future cq-examples upgrade or compiling camel-quarkus main branch.

To simplify, I assembled a project to simulate the behavior and questions outside of camel-quarkus:
https://github.com/aldettinger/ai-service-resolution-by-name

Hope it could help us move forward.

**Comment by geoand** [comment]
Hi,

Seems like we got the `@Named` support wrong. https://github.com/quarkiverse/quarkus-langchain4j/pull/1149 fixes that

**Comment by aldettinger** [comment]
Many thanks @geoand , gonna play with that udpate :)

**Comment by geoand** [comment]
🙏🏽
