### ISSUE TITLE
Allow `NoAuthModelAuthProvider` for proxy/sidecar base authentication 

### ISSUE THREAD

**Issue by dastrobu** [quarkiverse/quarkus-langchain4j#1128]
I like the new `ModelAuthProvider` interface introduced in version `0.22.0`, allowing the implementation of custom logic for setting the Authorization header.

It would be nice if the interface allowed the implementation of a `NoAuthModelAuthProvider`:

```java
@ApplicationScoped
public class NoAuthModelAuthProvider implements ModelAuthProvider {
    @Override
    public String getAuthorization(Input input) {
        return null;
    }
}
```

This should simply prevent setting any authorization header. Currently, it fails with:

```
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
        at org.jboss.resteasy.reactive.common.headers.HeaderUtil.headerToString(HeaderUtil.java:48)
```

The use case is that I have a deployment where the generation of the authorization header is offloaded to a sidecar, which injects the authorization header.

Prior to version `0.22.0`, I was setting a dummy API key in the config, which is simply ignored. This is a workaround but not very nice.

```
quarkus.langchain4j.azure-openai.api-key=dummy-key
```

I can create a pull request.

**Comment by geoand** [comment]
Thanks for reporting!

> I can create a pull request.

Please do. It makes sense to also update the Javadoc of `getAuthorization` to mention that returning `null` is allowed
