### ISSUE TITLE
Unified local models cache path

### ISSUE THREAD

**Issue by rsvoboda** [quarkiverse/quarkus-langchain4j#1133]
Downloaded models are currently stored into `~/.llama3java` and `~/.jlama` directories.

 * https://docs.quarkiverse.io/quarkus-langchain4j/dev/jlama.html#quarkus-langchain4j-jlama_quarkus-langchain4j-jlama-models-path
 * https://docs.quarkiverse.io/quarkus-langchain4j/dev/llama3.html#quarkus-langchain4j-llama3-java_quarkus-langchain4j-llama3-models-path

I propose to introduce `~/.langchain4j` directory and move the current content under it.

PROS:
 - one roof for the future additions on the local file sytem
 - intuitive place to look at when working with langchain4j

CONS:
 - it's a breaking change, but better to do it before 1.0

Mitigation strategy:
 - inform people in announce about changed structure

**Comment by geoand** [comment]
Makes sense to me. Would you like to contribute that @rsvoboda ?

**Comment by rsvoboda** [comment]
OK, I will look into it

**Comment by geoand** [comment]
🙏🏽

**Comment by rsvoboda** [comment]
I originally thought about having
```
~/.langchain4j/jlama/models
~/.langchain4j/llama3java/models
```

But I think we could put everything under `~/.langchain4j/models` as I think we do not need to differentiate the "runtime". 

Is that OK with you @geoand?

**Comment by geoand** [comment]
Yeah, I think that makes perfect sense
