### ISSUE TITLE
PgVectorAgroalPoolInterceptor doens't allow other profiles to be used while creating vector related attributes 

### ISSUE THREAD

**Issue by shrikanthkr** [quarkiverse/quarkus-langchain4j#1139]
I have a project where our profile name is local. While using quarkus langchain, with dev profile, necessary pgvector databases and extensions are added to the database. Since our profile is called as `local` am unable to find a way to override this behavior and build the same with devservices. Any directions here on how to workaround this?

**Comment by geoand** [comment]
Unfortunately I don't really understand what you are trying to do. Can you elaborate further?

cc @jmartisk

**Comment by jmartisk** [comment]
Do you mean that you need to get the `CREATE EXTENSION IF NOT EXISTS vector` query executed when the running Quarkus profile is named `local`?

**Comment by shrikanthkr** [comment]
Yes. @jmartisk that's what am trying to do.

**Comment by jmartisk** [comment]
Ok, I think it makes sense - how about we add a new boolean property `quarkus.langchain4j.pgvector.register-vector-pg-extension` that controls this, and it will be by default `true` only when running in `dev` or `test` mode, and can be explicitly turned on for other profiles too?

**Comment by shrikanthkr** [comment]
It would be really helpful if it's that way.

**Comment by shrikanthkr** [comment]
@jmartisk https://github.com/quarkiverse/quarkus-langchain4j/pull/1140/files would something like this help?
