### ISSUE TITLE
MCP client implementation

### ISSUE THREAD

**Issue by jmartisk** [quarkiverse/quarkus-langchain4j#1146]
This can be done after we get a LC4j version with https://github.com/langchain4j/langchain4j/pull/2240 in

Idea: We could create a configuration model like this
```
# one stdio-based MCP server
quarkus.langchain4j.mcp.server.server1.transport-type=stdio
quarkus.langchain4j.mcp.server.server2.command=npm exec @modelcontextprotocol/server-filesystem@0.6.2

# and one HTTP-based MCP server
quarkus.langchain4j.mcp.server.server2.transport-type=http
quarkus.langchain4j.mcp.server.server2.sse-url=http://localhost:3000/sse
```

and Quarkus would automatically generate a Tool provider that is backed by these two servers and register it in CDI to be picked up by AI services automatically

**Comment by jmartisk** [comment]
cc @langchain4j @geoand

**Comment by geoand** [comment]
👍🏽

**Comment by jmartisk** [comment]
BTW @edeandrea this will be a cool thing for demos :)

**Comment by geoand** [comment]
@mkouba is working a prototype to create MCP servers. Watch https://github.com/quarkusio/quarkus/issues/45054 for updates
