### ISSUE TITLE
AI has a broad meaning 

### ISSUE THREAD

**Issue by sshaaf** [quarkiverse/quarkus-langchain4j#115]
Reference to e.g. @RegisterAiService
Suggest to change AI service or the term AI used, as AI is a field of study and has a broad meaning. in this extension's case its more of a service for LLMs.

**Comment by geoand** [comment]
Indeed, however we followed the Langchain4j terminology here when coming up with the name

**Comment by sshaaf** [comment]
I noticed that too after posting this comment. Thanks for clarifying. If it's okay I will close this issue.

**Comment by geoand** [comment]
Thanks for checking!
