### ISSUE TITLE
Azure OpenAI auth - not possible to specify `api-key` for (default)embedding-model

### ISSUE THREAD

**Issue by flyinfish** [quarkiverse/quarkus-langchain4j#1154]
### BUG

when using an embedding model it is possible to specify a dedicated endpoint, but not a dedicated api-key
```
quarkus.langchain4j.azure-openai.embedding-model.resource-name=...
quarkus.langchain4j.azure-openai.embedding-model.api-key=unfortunately-ignored
```

when using ad different `resource-name` as in `quarkus.langchain4j.azure-openai` there will be a different `api-key`  needed as well.  but for `api-key` it falls back to `quarkus.langchain4j.azure-openai` or refusing to start if not present:
```

        SRCFG00014: Exactly of the configuration properties must be present: quarkus.langchain4j.azure-openai.api-key or quarkus.langchain4j.azure-openai.ad-token        
```        
### Expected Behaviour
should be possible to specify
```
quarkus.langchain4j.azure-openai.embedding-model.api-key=...
```

### Workaround
the workaround for some cases might be using a `@ModelName` this works as expected
```
quarkus.langchain4j.azure-openai.<namedembeddingmodel>.resource-name=...
quarkus.langchain4j.azure-openai.<namedembeddingmodel>.api-key=...
```
### Reproduce
<quarkus-langchain4j.version>0.22.0</quarkus-langchain4j.version>
https://github.com/flyinfish/quarkus-langchain4j--samples-azure-openai/tree/use-separate-resource-name/chatbot
https://github.com/flyinfish/quarkus-langchain4j--samples-azure-openai/blob/use-separate-resource-name/chatbot/.env-template

**Comment by geoand** [comment]
Thanks for reporting. 

The same issue exists for the chat model too, right?

**Comment by flyinfish** [comment]
> The same issue exists for the chat model too, right?

Yes!
Thanks

**Comment by geoand** [comment]
@edeandrea WDYT?

**Comment by edeandrea** [comment]
Sounds reasonable. If you're looking for me to take this up I don't think I'm going to have the bandwidth for a bit.

**Comment by geoand** [comment]
👍🏽

**Comment by geoand** [comment]
@flyinfish would you be interested in contributing this>

**Comment by flyinfish** [comment]
Can give a shot

**Comment by geoand** [comment]
👌
