### ISSUE TITLE
Azure OpenAI auth - insist in obsolete `api-key` when using ModelAuthProvider

### ISSUE THREAD

**Issue by flyinfish** [quarkiverse/quarkus-langchain4j#1155]
### BUG

when using an embedding model with auth by ModelAuthProvider quarkus-langchain4j insists in configuring 
quarkus-langchain4j
```
quarkus.langchain4j.azure-openai.api-key=...
```

Despite auth is done by ModelAuthProvider it refuses to start if not present:
```

        SRCFG00014: Exactly of the configuration properties must be present: quarkus.langchain4j.azure-openai.api-key or quarkus.langchain4j.azure-openai.ad-token        
```        
### Expected Behaviour
should start without `quarkus.langchain4j.azure-openai.api-key=workaround` as it does when only using chat-model

### Workaround
```
quarkus.langchain4j.azure-openai.api-key=workaround-to-be-ignored-completely
```
### Reproduce
<quarkus-langchain4j.version>0.22.0</quarkus-langchain4j.version>
https://github.com/flyinfish/quarkus-langchain4j--samples-azure-openai/tree/use-modelauthprovider/chatbot

**Comment by geoand** [comment]
Thanks for reporting!

@sberyozkin would you like to take a look at this one?

**Comment by sberyozkin** [comment]
Hi @geoand, I probably missed something in #1056, how would I test an embedding model with `azure-openai`, this is what we have https://github.com/quarkiverse/quarkus-langchain4j/blob/main/samples/secure-poem-multiple-models/src/main/resources/application.properties#L22 ?

**Comment by geoand** [comment]
No problem!

You would need to do something like `quarkus.langchain4j.openai.embedding-model.provider=azure-openai`

**Comment by sberyozkin** [comment]
Looks like I have to use `embedding-model` instead of the `chat-model`, sure, I'll try. I'll try to look at both issues, this one and the Gemini one, next week

**Comment by sberyozkin** [comment]
@geoand Yeah, thanks for confirming :-)

**Comment by geoand** [comment]
🙏🏽
