### ISSUE TITLE
ChatBot responses are a liitle bit slow

### ISSUE THREAD

**Issue by sberyozkin** [quarkiverse/quarkus-langchain4j#116]
Sorry if it is a duplicate or requires a correct memory usage, I'm just trying to catch up with some demos.

So, when I went to `localhost:8080` in the chat bot sample demo, I was not sure what to ask so I started with:

`What should I do next` - it thought for about 10-11 secs, and offered a summary of the available accounts, mentioning the saving account among other options.

My next question was:
`Please tell me more about the saving account` - it thought for a little bit longer, may be 13-14 secs, and then responded.

Then if I stop and start the demo again, the same 10/13 seconds delay is observed when I ask `exactly` the same questions - even though this is a restart, I thought, given that the questions were already asked with the same API key, the model should already be trained somehow.

I guess this is about configuring the memory correctly managed by Redis (or Infinispan)  or may be adding some parameters to the OpenAI builder to instruct it to remember some of its own responses ?

It would be good, if after the restart of the demo, a much faster response is produced (expecially if it is asked exactly by the same authenticated user), though I appreciate it may be difficult to achieve 

Thanks

**Comment by geoand** [comment]
> I thought, given that the questions were already asked with the same API key, the model should already be trained somehow.

That's not how it works :). Every API call is completely stateless and there is no per-account training.

As for the memory issue, we don't really want to have chat memory surviving application restarts by default (even if Redis or Infinispan were being used), as that would mean that there is no way to purge chats.  

> It would be good, if after the restart of the demo, a much faster response is produced (expecially if it is asked exactly by the same authenticated user), though I appreciate it may be difficult to achieve

I understand where this is coming from, but although it would be useful for a demo, it's certainly not what you want in a real application

**Comment by sberyozkin** [comment]
@geoand This is what I've been thinking about   , why, given the same question being asked,  OpenAI does not have its own way of optimising, as a user I'd have certainly appreciated a faster response time.

Agreed though this extension managing it with caching is not a good idea,  but trying to figure out how to make OpenAI reply faster than 10 secs to nearly identical questions is worth it IMHO

**Comment by geoand** [comment]
> Agreed though this extension managing it with caching is not a good idea, but trying to figure out how to make OpenAI reply faster than 10 secs to nearly identical questions is worth it IMHO

Yeah, that certainly makes sense. However, keep in mind that answers are not deterministic, so what if the answer was not good and we wanted to try again?
