### ISSUE TITLE
Ability to serve a default response?

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-langchain4j#130]
Since integrating with OpenAI costs real money, should there be a way that I can serve a default response if I want to "turn off" the integration at runtime? Maybe when I'm running in dev mode or if I'm doing a quick demo I don't want it to make "real" calls to an openai provider.

**Comment by edeandrea** [comment]
I certainly could add my own logic to whatever code I have that calls my ai service, but it would be nice if the library itself could support it.

**Comment by geoand** [comment]
How do you envision this would look like?

**Comment by edeandrea** [comment]
There would be some new config property, that when set to `true`, first the api-key (or the other required azure properties if using the azure extension) would no longer be required.

Then, maybe at the point of making the http request, some runtime exception is thrown instead? Maybe some new `ClientCallBypassedException` or something. 

Then in the ai service interface I could use a fallback, either globally for all exceptions, or just for that specific exception, to return some default of my choice.

This way it keeps the extension from caring about what to do in that case?

Just a thought.

**Comment by geoand** [comment]
My question was really how this would looks from a user code pespective. What would the user set / change / configure?

**Comment by edeandrea** [comment]
I can whip up some sample code when I get to my desk if you'd like.

**Comment by geoand** [comment]
Sure, I'd like to see what you have in mind.

**Comment by edeandrea** [comment]
Here's what I'm thinking (I'm not good at naming things and I'm just pulling things out of thin air :) ).

In `application.properties`:

```properties
quarkus.langchain4j.openai.make-live-requests=false # This would be `true` by default
# OR
quarkus.langchain4j.azure-openai.make-live-requests=false # This would be `true` by default
```

The fact that I set the property to `false` would then make it so other properties, like `api-key`, are no longer required. When the service went to make the downstream call, if `make-live-requests==false` it would throw some new exception type (`ClientCallBypassedException`).

Then in my code I would do:

```java
@RegisterAiService
public interface OpenAiNarrationService extends NarrationService {
  @SystemMessage("You are a marvel comics writer, expert in all sorts of super heroes and super villains.")
  @UserMessage("""
    Narrate the fight between a super hero and a super villain.

    During the narration, don't repeat "super hero" or "super villain".
    
    Write 4 paragraphs maximum. Be creative.
    
    The narration must be:
    - G rated
    - Workplace/family safe
    - No sexism, racism, or other bias/bigotry
    
    Here is the data you will use for the winner:
    
    +++++
    Name: {fight.winnerName}
    Powers: {fight.winnerPowers}
    Level: {fight.winnerLevel}
    +++++
    
    Here is the data you will use for the loser:
    
    +++++
    Name: {fight.loserName}
    Powers: {fight.loserPowers}
    Level: {fight.loserLevel}
    +++++
    
    Here is the data you will use for the fight:
    
    +++++
    {fight.winnerName} who is a {fight.winnerTeam} has won the fight against {fight.loserName} who is a {fight.loserTeam}.
    
    The fight took place in {fight.location.name}, which can be described as {fight.location.description}.
    +++++
    """)
  @Fallback(fallbackMethod = "narrateFallback")
  String narrate(Fight fight);

  default String narrateFallback(Fight fight, ClientCallBypassedException clientCallBypassed) {
    // It would be nice in here if I had access to the CDI context and could use other beans to form a response
    // Maybe I'm storing something as a property inside an @ConfigMapping class I'd want to read in here
    return "Some fallback because make-live-requests was turned off";
  }

  default String narrateFallback(Fight fight) {
    // It would be nice in here if I had access to the CDI context and could use other beans to form a response
    // Maybe I'm storing something as a property inside an @ConfigMapping class I'd want to read in here
    return "some fallback because something else happened";
  }
}
```

**Comment by geoand** [comment]
So this way it would only work if the fallback annotation was present. That doesn't seem ideal, no?

**Comment by edeandrea** [comment]
In this case yes the fallback annotation would have to be there yes. I was trying to think of a way that was least invasive for the library. Otherwise the rest call would have to return _something_. Using this approach the rest client stays "dumb", meaning it doesn't need to know about any particular response it needs to serve.

Just a thought though.

**Comment by geoand** [comment]
Right, I need to ponder on it

**Comment by edeandrea** [comment]
If I went ahead and brought up a PR that implemented this exception-based approach, would you entertain it? Or do you need to shake out the best design first? I'm really itching to have this capability, as when running locally (or in other environments where my credit card isn't available) I'd really like the app to work.

**Comment by edeandrea** [comment]
Upon starting to look at implementation details it looks like I'll have to do something in upstream langchain4j first. The config property/flag would need to get into the langchain4j model classes (`OpenAiChatModel`/etc).

**Comment by edeandrea** [comment]
This is because things like `OpenAiRecorder` directly return the upstream Langchain4j model classes which are then used by `QuarkusOpenAiClient.QuarkusOpenAiClientBuilderFactory`. There doesn't seem to be a way to feed `QuarkusOpenAiClient` with a property without going through the Langchain4j model objects.

On the Azure side it looks like the extension manages its own set of model classes.

Would it be worthwhile on the openai "vanilla" side to make it so the extension has its own set of model objects? These could extend the ones provided by upstream, so there wouldn't be much change actually.

I could work that into this change, or create a separate PR just for that if you'd like. Let me know what you think.

**Comment by geoand** [comment]
> Would it be worthwhile on the openai "vanilla" side to make it so the extension has its own set of model objects? These could extend the ones provided by upstream, so there wouldn't be much change actually.

Sure, extending upstream sounds fine

**Comment by geoand** [comment]
Unfortunately that doesn't seem to be possible due to how Langchain4j is done.

**Comment by edeandrea** [comment]
In the Quarkus langchain extension, how does `QuarkusOpenAiClient.Builder` get invoked and the builder methods on it called? I see the factory getting registered in https://github.com/quarkiverse/quarkus-langchain4j/blob/main/openai/openai-common/runtime/src/main/resources/META-INF/services/dev.ai4j.openai4j.spi.OpenAiClientBuilderFactory, but where do the factory methods actually get invoked on the builder?

**Comment by geoand** [comment]
```java
public abstract class OpenAiClient {
    public static OpenAiClient.Builder builder() {
        for (OpenAiClientBuilderFactory factory : ServiceHelper.loadFactories(OpenAiClientBuilderFactory.class)) {
            return factory.get();
        }
        // fallback to the default
        return DefaultOpenAiClient.builder();
    }
}
```

The extension provides `QuarkusOpenAiClientBuilderFactory` to hook into that

**Comment by edeandrea** [comment]
Right I saw that, but where do the methods on the builder actually get invoked within the extension? When application code uses `@RegisterAiService` the `QuarkusOpenAiClient.Builder` and its methods must get invoked somewhere in order to create the `QuarkusOpenAiClient` instance and register it as a bean.

**Comment by geoand** [comment]
`@RegisterAiService` uses the `chatModel` that is configured in `OpenAiRecorder`

**Comment by edeandrea** [comment]
Can you point me to where in the codebase this actually happens? At some point a bean instance for `QuarkusOpenAiClient` is registered somewere, no? I tried searching for references on `QuarkusOpenAiClient` but didn't find it, or maybe I overlooked it. Where are the `QuarkusOpenAiClient.Builder` methods actually called?

**Comment by geoand** [comment]
> Can you point me to where in the codebase this actually happens? At some point a bean instance for QuarkusOpenAiClient is registered somewere, no?

Nope, an instance of the client is created per model (these models are the beans). 

So in upstream Langchain4j when 

```java
        this.client = OpenAiClient.builder()
                .openAiApiKey(apiKey)
                .baseUrl(baseUrl)
                .organizationId(organizationId)
                .callTimeout(timeout)
                .connectTimeout(timeout)
                .readTimeout(timeout)
                .writeTimeout(timeout)
                .proxy(proxy)
                .logRequests(logRequests)
                .logResponses(logResponses)
                .build();
```

happens, the client is created

**Comment by edeandrea** [comment]
Gotcha! That was the missing link I've been looking for! So back to my previous comment about having our own models that extend the Langchain4j ones - that would give us the ability to customize the builder.

Maybe one enhancement for upstream langchain4j would be to stub out to a separate method where it does that. That way it could be overridden in our own model classes and we could add additional attributes.

The current way it works is that getting new attributes onto that builder involve changes to https://github.com/ai-for-java/openai4j which then have to be pulled into langchain4j, then pulled into here. It would be nice if we could enhance it for things specific to Quarkus that are above & beyond.

**Comment by geoand** [comment]
> It would be nice if we could enhance it for things specific to Quarkus that are above & beyond.

Sure yeah

**Comment by edeandrea** [comment]
Once langchain4j/langchain4j#549 is released then this will consume that.
