### ISSUE TITLE
Allow for specifying the organization id in the configuration

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-langchain4j#131]
See https://platform.openai.com/docs/api-reference/organization-optional - allow the organizationId to be specified in the configuration.

**Comment by geoand** [comment]
This would need to first be added to upstream langchain4j. Can you open an issue there please?

**Comment by edeandrea** [comment]
https://github.com/langchain4j/langchain4j/issues/344

**Comment by geoand** [comment]
Thanks!

**Comment by edeandrea** [comment]
https://github.com/langchain4j/langchain4j/pull/364 submitted.

**Comment by edeandrea** [comment]
Once https://github.com/langchain4j/langchain4j/pull/364 is merged & released I'll do a PR here too.
