### ISSUE TITLE
In azure openai extension, need a way to override the base url

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-langchain4j#149]
The config in the `azure-openai` extension allows for specifying the `resourceName` and `deploymentId` and then it constructs the base url as

```java
String.format("https://%s.openai.azure.com/openai/deployments/%s", runtimeConfig.resourceName(), runtimeConfig.deploymentId())
```

as in

https://github.com/quarkiverse/quarkus-langchain4j/blob/3766531dcf0e1bd21488393abfbbe66b61f9a968/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java#L92-L95

This is great when running against the real thing, but if you want to be able to test this using something like WireMock, you can't. We need a way to specify the base url.

Maybe in `Langchain4jAzureOpenAiConfig` something like this?

```java
@WithDefault("https://${quarkus.langchain4j.azure-openai.resource-name}.openai.azure.com/openai/deployments/${quarkus.langchain4j.azure-openai.deployment-id}")
String baseUrl();
```

**Comment by geoand** [comment]
Good point!

Feel free to go ahead and open a PR with the exact change you propose!

**Comment by edeandrea** [comment]
Does using variable interpolation like that inside an `@WithDefault` annotation actually work?

**Comment by geoand** [comment]
It should
