### ISSUE TITLE
Sample Does Not Run 

### ISSUE THREAD

**Issue by linktech1** [quarkiverse/quarkus-langchain4j#150]
I get the following error when trying to run the Fraud Detection sample:

Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
	SRCFG00014: The config property quarkus.langchain4j.openai.api-key is required but it could not be found in any config source
	at io.quarkiverse.langchain4j.openai.runtime.OpenAiRecorder.chatModel(OpenAiRecorder.java:25)

**Comment by geoand** [comment]
You need to supply an OpenAI API key.

For example:

`quarkus.langchain4j.openai.api-key=mykey`

**Comment by linktech1** [comment]
Added the API Key now I get:

dev.ai4j.openai4j.OpenAiHttpException: {
    "error": {
        "message": "The model `gpt-4-1106-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

**Comment by geoand** [comment]
We use GPT 3.5 turbo by default, so you don't absolutely need to set a model.

That said, it seems like you configured one that your accound does not have access to.

**Comment by linktech1** [comment]
This is the entry in the Fraud Detection sample application.properties. I did not change. I guess I'll just comment it out...

quarkus.langchain4j.openai.chat-model.model-name=gpt-4-1106-preview

**Comment by geoand** [comment]
Interesting... It works for my account.

That said, I have no idea what policies OpenAI has in place for limiting models

**Comment by linktech1** [comment]
It looks like I have to pay separate from my ChatGPT+ account to get the current models.

**Comment by geoand** [comment]
Ah, correct! The API access is a different AFAIk

**Comment by linktech1** [comment]
After commenting out the model I now get:

dev.ai4j.openai4j.OpenAiHttpException: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

I tried putting in couple of different CCs but seems to be a problem with payment service....
