### ISSUE TITLE
OpenAiRestApiJacksonProvider affecting non extension clients

### ISSUE THREAD

**Issue by yvesv** [quarkiverse/quarkus-langchain4j#164]
Ok, so I'm quite new to Quarkus and figuring things out. But after adding the extension to my projects. Other clients in my project weren't properly deserializing anymore because the extension 'forced' to use the OpenAiRestApiJacksonProvider. I'm currently searching for a way to work around this issue. But preferably of course the extension only affects the clients of the extension.

**Comment by geoand** [comment]
Very interesting.

Any chance you can attach a sample project that shows this problem?

**Comment by geoand** [comment]
https://github.com/quarkiverse/quarkus-langchain4j/pull/165 should fix it

**Comment by yvesv** [comment]
Wow. You are fast! Thanks.

**Comment by geoand** [comment]
Unfortunately CI is complaining, so I'll have to take a closer look on Monday.

**Comment by geoand** [comment]
See https://github.com/quarkiverse/quarkus-langchain4j/pull/165#issuecomment-1858871062. 

This means that it will take a few days to get a new release out with the fix

**Comment by yvesv** [comment]
Thanks. Did a quick check, and this indeed fixed the issue.

**Comment by geoand** [comment]
Thanks for checking!
