### ISSUE TITLE
Create a DevService for ollama

### ISSUE THREAD

**Issue by lordofthejars** [quarkiverse/quarkus-langchain4j#168]
Create a DevService for ollama container as done in https://github.com/langchain4j/langchain4j/blob/main/langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/AbstractOllamaInfrastructure.java

I am going to work on that, providing a PR.

I created this issue to create a branch with this name. We can always rename later.

**Comment by geoand** [comment]
👌

**Comment by geoand** [comment]
Done in #168
