### ISSUE TITLE
Allow specifying the RAG retriever bean type for an AiService

### ISSUE THREAD

**Issue by andreas-eberle** [quarkiverse/quarkus-langchain4j#184]
Currently, if you define a bean which implements `Retriever<TextSegment>`, it will be used by all AiServices in your application. This is probably not what most people want because this sends a lot of extra tokens and data that might not be relevant or even unwanted for other AiServices in your application.

The current way to get around this is to implement a `Supplier<Retriever<TextSegment>>` in a class and provide the Retriever from there. However, the supplier is not a bean and thus you need to manually get the required embedding store and embedding model from ARC. This does not feel "quarkusy" at all because it does not make proper use of CDI.

Instead, I propose to add a new property to the `RegisterAiService` annotation like this:

`@RegisterAiService(retriever = MyDocumentRetriever.class)`

So instead of creating a supplier that provides the retriever, one would create a bean (`MyDocumentRetriever`) and Quarkus would inject it depending on the type specified in the annotation. The big benefit I see in this is that you can just define your normal bean and Quarkus picks it up depending on the type you specify.

This gives the user maximum flexibility and convenience because you can use normal CDI beans. 

Also see Zulip discussion: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20Langchain.3A.20Chat.20Memory.20Management.20Questions/near/409195506

**Comment by geoand** [comment]
Currently the various settings on the annotations are deliberately very consistent in their usage. 
This would introduce a different way of doing things for the retriever, which I would like to wait before adding 
so we can really determine if what is described here is a common pattern.

**Comment by andreas-eberle** [comment]
I think for RAG, it is quite important to be able to select the RAG retriever per AI service. And even, to not have it auto-applied. 

Currently, the retriever is auto-applies to all my AIServices in a single Quarkus instance and this costs me tokens and might leak data into an AI Integration that is not concerned with certain data. E.g. I might have a poem service and an internal wiki assistant which uses RAG to get internal documents. Somebody using the poem service does not need and should not see the the internal wiki documents. 

Another thought: isn't the way tools are specified exactly they way I proposed for the retriever? There, we also specify the class of the bean that quarkus should use. And I think the leaking and token usage arguments are also the same for tools than for the retriever. 

Thinking of the tools, it also seems we have a precedent for doing it this way :D 

What do you think?

**Comment by geoand** [comment]
Interesting point that the `retriever` should be considered more like a tool than like memory. 

I do think it's a good point and am inclined to move to this direction. @cescoffier WDYT?

**Comment by cescoffier** [comment]
Yes, it's not even for a specific method of an AiService.

**Comment by geoand** [comment]
I'll have a look at this later this week then.

**Comment by andreas-eberle** [comment]
Maybe it could make sense (longer term) to either allow the AIService annotation for methods or to split it up into multiple separate annotations which then can be used on the methods as well. E.g. ´@DocumentRetriever`, ´@Tools`  or so.

**Comment by geoand** [comment]
I would prefer not to add new annotations unless we really have to.

**Comment by geoand** [comment]
#225 is what I have in mind

**Comment by andreas-eberle** [comment]
Thanks! Do you know when the next version will be released/which version number will contain this change? :)
