### ISSUE TITLE
The email-a-poem sample doesn't work

### ISSUE THREAD

**Issue by nicolasduminil** [quarkiverse/quarkus-langchain4j#191]
Hello,

Tried to run the `email-a-poem` sample. I had to add the property `quarkus.langchain4j.openai.api-key` with my API key and then trying to `curl http://localhost:8080/email-me-a-poem`, I got the following exception:

    2023-12-30 18:38:54,828 INFO  [io.qua.lan.ope.OpenAiRestApi$OpenAiClientLogger] (vert.x-eventloop-thread-0) Request:
    - method: POST
    - url: https://api.openai.com/v1/chat/completions
    - headers: [Accept: application/json], [api-key: sk...ud], [Authorization: Bearer sk-RF...ud], [Content-Type: application/json],    [User-Agent: Resteasy Reactive Client], [content-length: 501]
    - body: {"model":"gpt-3.5-turbo","messages":[{"role":"system","content":"You are a professional poet"}, {"role":"user","content":"Write a poem about Quarkus. The poem should be 4 lines long. Then send this poem by email."}],"temperature":1.0,"top_p":1.0,"presence_penalty":0.0,"frequency_penalty":0.0,"tools":[{"type":"FUNCTION","function":{"name":"sendAnEmail","description":"send the given content by email","parameters":{"type":"object","properties":{"content":{"type":"string"}},"required":["content"]}}}]}
    2023-12-30 18:38:55,063 INFO  [io.qua.lan.ope.OpenAiRestApi$OpenAiClientLogger] (vert.x-eventloop-thread-0) Response:
    - status code: 400
    - headers: [Date: Sat, 30 Dec 2023 17:38:55 GMT], [Content-Type: application/json], [Content-Length: 167], [Connection: keep-alive], [access-control-allow-origin: *], [openai-organization: user-ejc8mjulfh1fsxv6jwubndfm], [openai-processing-ms: 4], [openai-version: 2020-10-01], [strict-transport-security: max-age=15724800; includeSubDomains], [x-ratelimit-limit-requests: 10000], [x-ratelimit-limit-tokens: 60000], [x-ratelimit-limit-tokens_usage_based: 60000], [x-ratelimit-remaining-requests: 9999], [x-ratelimit-remaining-tokens: 59952], [x-ratelimit-remaining-tokens_usage_based: 59952], [x-ratelimit-reset-requests: 8.64s], [x-ratelimit-reset-tokens: 48ms], [x-ratelimit-reset-tokens_usage_based: 48ms], [x-request-id: 1c6a71534308ce8cfde114c56ce56e69], [CF-Cache-Status: DYNAMIC], [Set-Cookie: __cf_bm=08L8C4Z1TWOGx.BS04JuXlz6V1NJL5qxB4Q9qn4a0M8-1703957935-1-AV1lUGvouAFZvTT4CtWlgwr0AvGUc/6apoVFr5ZEuyBVCOic8MXhI5SBvsaa9oqp5YEuVKGOIHvZUNW8sN87fP4=; path=/; expires=Sat, 30-Dec-23 18:08:55 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None], [Set-Cookie: _cfuvid=M6hgU7SgJFt70SMSYxfs1frnmBT7h94hTl25Ay.9kVA-1703957935016-0-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None], [Server: cloudflare], [CF-RAY: 83dc0f24ba837921-CDG], [alt-svc: h3=":443"; ma=86400]
    - body: {
      "error": {
        "message": "'FUNCTION' is not one of ['function'] - 'tools.0.type'",
        "type": "invalid_request_error",
        "param": null,
        "code": null
      }
    }

Not sure what might be wrong here. Probably something related to the email service config ? Please advise.

Many thanks in advance.

Kind regards,

Nicolas

**Comment by geoand** [comment]
Thanks a lot for reporting!

Indeed this is a problem with the current version of the code, and I've opened #192 to address it (no tests yet, as I don't have much time now, but I'll add some next week).

**Comment by nicolasduminil** [comment]
@geoand : Many thanks for your reply. I didn't manage to find any `0.5.2` tag in the repo. However, I found the `0.5.1` one that I tested and I confirm that it works. There are still a couple of insignificant details that I would like to report anyway:
- The poem is generated as expected but, for some reason, instead of sending it by email, the following message is displayed:

    `I'm sorry, but it seems that I am currently unable to send emails. However, I can still provide you with the poem about Quarkus`

This is probably related to my SMTP config, as follows: (I'm using AWS SES):

    quarkus.mailer.host=${ses.smtp}
    quarkus.mailer.port=587
    quarkus.mailer.username=${ses.user}
    quarkus.mailer.password=${ses.password}
    quarkus.mailer.start-tls=REQUIRED
    quarkus.mailer.login=REQUIRED
    quarkus.mailer.from=${ses.from}
    quarkus.mailer.mock=false 

If you see anything wrong in this config, please let me know.

- At the end of the log the following message is displayed:

    `2023-12-31 18:46:13,803 SEVERE [io.qua.ope.run.exp.otl.VertxGrpcExporter] (vert.x-eventloop-thread-3) Failed to export spans. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317`

Again, not sure where from this error comes, accordingly, I'd be very obligated to you if you could let me know how to fix it.

Many thanks in advance.

Kind regards,

Nicolas

**Comment by geoand** [comment]
As for the email config, I am unfortunately not able to provide any insight.

The warning about exporting spans, you can safely ignore as you have not configured any OpenTelemetry related settings

**Comment by nicolasduminil** [comment]
Thanks.
