### ISSUE TITLE
LangChain update: PDFDocumentParser was moved to a separate dependency; Can it be provided with the extension

### ISSUE THREAD

**Issue by andreas-eberle** [quarkiverse/quarkus-langchain4j#199]
With the update of LangChain4J to version 0.25.0, the PDFDocumentParser was moved to its own dependency `dev.langchain4j:langchain4j-document-parser-apache-pdfbox:0.25.0` and renamed to `ApachePdfBoxDocumentParser`. 

The same applies for the Office / Apache POI parser. It was moved to `dev.langchain4j:langchain4j-document-parser-apache-poi:0.25.0`.

Do you think it makes sense to expose these dependencies to either integrate them in the Quarkus LangChain dependency or expose them as a separate extension? 

Something like
`io.quarkiverse.langchain4j:quarkus-langchain4j-apache-pdfbox-document-parser` ? 

Right now, users will need to maintain the version of the Quarkus extension and the version of the used langchain library separately.

**Comment by geoand** [comment]
An alternative would be for us to provide our own BOM.

WDYT @cescoffier ?

**Comment by cescoffier** [comment]
A bom would be great. We will have more dependencies to lock in the future.

**Comment by geoand** [comment]
@maxandersen does the Quarkus tooling support adding a bom to the generated project when an extension provides one?

**Comment by maxandersen** [comment]
No. Not currently afaik. 

Operatorsdk and others has similar needs. 

Cc @aloubyansky 

That said - not sure solving this with a bom is sustainable long term. But for now with everything moving so fast it would be very useful.

**Comment by geoand** [comment]
We now have a BOM, so let's close this
