### ISSUE TITLE
Dev UI page for experimenting with image models

### ISSUE THREAD

**Issue by jmartisk** [quarkiverse/quarkus-langchain4j#202]

**Comment by jmartisk** [comment]
I have a basic implementation of a page that just injects the pre-configured ImageModel from CDI and uses that to generate pictures.
Been thinking whether we should also allow the user to set some model parameters inside the page and then dynamically create a model with these parameters. The problem with this is that when we add more models beyond OpenAI, their set of configuration options will be different. And also that the `core` module doesn't have compile-time dependencies on the particular model implementations, so it will be tricky to dynamically create the models.

**Comment by geoand** [comment]
> Been thinking whether we should also allow the user to set some model parameters inside the page and then dynamically create a model with these parameters

Yeah, that's what I had also proposed for the chat page as well. I think it's super useful for experimentation.  

> The problem with this is that when we add more models beyond OpenAI, their set of configuration options will be different

That's something we can address later on - OpenAI is by far the most widely used model at this point.

**Comment by jmartisk** [comment]
Ok I'll try, it will be openai-specific for the time being

**Comment by geoand** [comment]
👌🏼
