### ISSUE TITLE
upgrade fom 0.4 to 0.6.1 breaks with invalid_request_error

### ISSUE THREAD

**Issue by maxandersen** [quarkiverse/quarkus-langchain4j#212]
Do:

```
export QUARKUS_LANGCHAIN4J_OPENAI_API_KEY=yoursecretkey
jbang https://github.com/maxandersen/javaadvent-2023-quarkus-ai-scripting/blob/main/devhelper.java
```

and it should work.

Now just change 
`//DEPS io.quarkiverse.langchain4j:quarkus-langchain4j-openai:0.4.0` to `//DEPS io.quarkiverse.langchain4j:quarkus-langchain4j-openai:0.6.1`

and I get:

```
2024-01-08 23:13:00,175 WARN  [dev.lan.int.RetryUtils] (main) Exception was thrown on attempt 1 of 3: dev.ai4j.openai4j.OpenAiHttpException: {
  "error": {
    "message": "None is not of type 'string' - 'messages.0.name'",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

that issue is fixed in https://github.com/quarkiverse/quarkus-langchain4j/pull/211
but updating to 999-SNAPSHOT I then get:

"Class 'devhelper$ProjectHelper' which is annotated with @RegisterAiService has configured tools support, but no ChatMemoryProvider configuration is present. Please set up chatMemoryProvider in order to use tools. A ChatMemory that can hold at least 3 messages is required for the tools to work properly. While the LLM can technically execute a tool without chat memory, if it only receives the result of the tool's execution without the initial message from the user, it won't interpret the result properly."

which contradicts with  the docs afaics:

"The default configuration values result in the usage of dev.langchain4j.memory.chat.MessageWindowChatMemory with a window size of ten"

**Comment by maxandersen** [comment]
woth nothing that if i use latest main 999-snapshot I Get:

"Class 'devhelper$ProjectHelper' which is annotated with @RegisterAiService has configured tools support, but no ChatMemoryProvider configuration is present. Please set up chatMemoryProvider in order to use tools. A ChatMemory that can hold at least 3 messages is required for the tools to work properly. While the LLM can technically execute a tool without chat memory, if it only receives the result of the tool's execution without the initial message from the user, it won't interpret the result properly."

maybe related?

**Comment by maxandersen** [comment]
reading docs in main says:

"It leverages the available configuration options under quarkus.langchain4j.chat-memory to construct the ChatMemoryProvider.

    The default configuration values result in the usage of dev.langchain4j.memory.chat.MessageWindowChatMemory with a window size of ten
"

exception says I need 3 messages min memory, and doc says it has 10 by default...

what am I missing ? :)

**Comment by maxandersen** [comment]
original issue fixed in https://github.com/quarkiverse/quarkus-langchain4j/pull/211 so now its more the memory exception which I can't get to line up with docs and having to do as samples and provide custom memory for all service doesn't seem right to me?

**Comment by maxandersen** [comment]
updating from 3.6.3 to 3.6.4 seem to fix it?

**Comment by geoand** [comment]
Yes, you need 3.6.4
