### ISSUE TITLE
Moderation model Dev UI page

### ISSUE THREAD

**Issue by jmartisk** [quarkiverse/quarkus-langchain4j#228]
As we have a page for chatting with chat models, we could also have something for moderation models. Perhaps it could just allow you to send a message and check whether it gets flagged, and it would show the category scores as a table - I guess that would be specific to OpenAI now, the general `ModerationResponse` only contains a `flagged` boolean.

Just as we allow tuning some config on the Image model page, this would allow you to choose the particular model (OpenAI supports two at the moment).

@geoand WDYT?

**Comment by geoand** [comment]
It definitely sounds useful!
