### ISSUE TITLE
Allow adding SystemMessage on the type

### ISSUE THREAD

**Issue by iocanel** [quarkiverse/quarkus-langchain4j#255]
Currently `SystemMessage` can only be added on the method. To avoid repeating the same message again and again, it should be possible to also add it on the type and having the same effect as adding it to all methods.

The question is `what happens when user adds it on both places ?`

There are a couple of options here ?

1. Append methods system message to the type system message (similar to `@Path` in jax-rs).
2. Replace types system message, with methods system message.
3. Add an additional parameter in the annotation that specifies the behavior.

Personally, I favor `1` because its something already familiar to users.

**Comment by iocanel** [comment]
Also, if we agree on the approach I'd like to take a stub at it.

**Comment by geoand** [comment]
I assume this is the same thing as https://github.com/quarkiverse/quarkus-langchain4j/issues/10, correct?

**Comment by geoand** [comment]
In any case, it would require https://github.com/langchain4j/langchain4j/pull/546. 

As for the behavior if it's on both the class and method, I think that `2` makes the most sense

**Comment by iocanel** [comment]
Closing as dublicate
