### ISSUE TITLE
Authorization header is not masked properly

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-langchain4j#264]
I've only tested with the `openai` and `azure-openai` extensions, so I can't say whether or not this is present in the others, but it seems that if `logRequests` is set to `true`, the `Authorization` header is exposed in the log along with its value. This could leak the users api key.

The `api-key` header is masked. See screenshot (I've not captured the entire key so as to not leak mine :) )

![image](https://github.com/quarkiverse/quarkus-langchain4j/assets/363447/e2699ab6-bf3c-40ae-8a92-a54a73da1b9a)

**Comment by geoand** [comment]
Thanks.

I'm off for the weekend, so if you want this in, I propose giving it a go.

It should be fairly easy

**Comment by edeandrea** [comment]
I think I see what the problem is. In `OpenAiClientLogger` there is `private static final Pattern BEARER_PATTERN = Pattern.compile("(Bearer\\s*sk-)(\\w{2})(\\w+)(\\w{2})");`

Which seems fine when talking to OpenAI, but when talking to Azure OpenAI, the key format is in a different format (i.e. doesn't begin with `sk-`).

I guess one question is - why even have the `Authorization` header when talking to Azure Open AI (and why have the `api-key` header when talking to OpenAI?

**Comment by geoand** [comment]
Because it allows sharing the same client between those two providers

**Comment by edeandrea** [comment]
That could still be accomplished. The client could be smart enough to set the correct header.

https://github.com/quarkiverse/quarkus-langchain4j/blob/c9bf7a95e0d0b13983b8d18802f47758cc33f829/openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/QuarkusOpenAiClient.java#L109-L116

**Comment by geoand** [comment]
Feel free to implement said improvement

**Comment by edeandrea** [comment]
> Feel free to implement said improvement

Spoken like a true OSS project maintainer :D

I'll see what I can do today.

**Comment by geoand** [comment]
No rush, I won't release until next week

**Comment by edeandrea** [comment]
See #265
