### ISSUE TITLE
Add support for the OpenAI response_format configuration

### ISSUE THREAD

**Issue by PierreBtz** [quarkiverse/quarkus-langchain4j#274]
Hello folks

I often observed issues with a model not outputting proper json despite the prompt specifically asking for json ("you must return a valid json object, with no control characters" etc...).
This obviously can be mitigated by Retries but it remains a waste of token and API calls.

OpenAI offers a [response_format](https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format) on some of their models, allowing to force the model to output a specific format (mainly json at this stage).

I did some testing and it seems this setting fixes the issue. Langchain4j surfaces this setting (eg https://github.com/langchain4j/langchain4j/blob/b36315056ef6a4f4a021bd4cfcc97ac0d6c1a4de/langchain4j/src/test/java/dev/langchain4j/service/AiServicesIT.java#L249) and I'd like to make it accessible in the `ChatModelConfig` of this project.

I have [a working branch locally](https://github.com/PierreBtz/quarkus-langchain4j/commit/00904db478c6895d04f8430efb5df8e16fa704fe) but before I go ahead, polish it and open a PR I want to make sure with you it's something you want.

**Comment by geoand** [comment]
That would be great!
