### ISSUE TITLE
azure openai doesn't support all arguments

### ISSUE THREAD

**Issue by andrekullmann** [quarkiverse/quarkus-langchain4j#285]
I'm using azure openai 

model=gpt-35-turbo
api-version=2023-05-15

I receive the error 
"Unrecognized request arguments supplied: frequencyPenalty, presencePenalty, topP"

In the application.properties I can not set the values to null.

**Comment by geoand** [comment]
Can you please enhance the description of the issue with the entire stacktrace?

**Comment by geoand** [comment]
Furthermore, can you post the content of the request and response when

```properties
quarkus.langchain4j.azure-openai.log-requests=true
quarkus.langchain4j.azure-openai.log-responses=true
```

are enabled?

**Comment by andrekullmann** [comment]
**Request
```
{
"model":"gpt-3.5-turbo","messages":[{"role":"user","content":"    Hello, my name is Hello\n","name":"andre"}],"temperature":1.0,"topP":1.0,"presencePenalty":0.0,"frequencyPenalty":0.0
}
```

**Resonse**
```
{
  "error": {
    "message": "Unrecognized request arguments supplied: frequencyPenalty, presencePenalty, topP",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

**Comment by geoand** [comment]
Thanks!

**Comment by geoand** [comment]
@edeandrea @agoncal do you know if these properties should never be sent for Azure OpenAI?

**Comment by edeandrea** [comment]
I believe they should be sent (or at least as of last week :) ). I'm using those properties with azure openai without issue.

They are there as optional properties in the rest API reference: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference

**Comment by geoand** [comment]
🙏

**Comment by edeandrea** [comment]
Although it looks like their format is a little different (there are underscores). I wonder if that's a recent change.

**Comment by edeandrea** [comment]
I'm not sure why in @andrekullmann 's request the parameters are different. It was working fine for me earlier this week when I did the "what's new with the superheroes" quarkus insights session. I talked live to azure openai.

I even have tests in the superheroes that prove those attributes are being set properly on the request. I have wiremock doing request matching.

**Comment by andrekullmann** [comment]
Thank you guys.
I think I've found the issue. 
After update quarkus from 3.5.2 to 3.7.2 it works as expected.
Sorry for the circumstances.

**Comment by geoand** [comment]
Thanks for the update!
