### ISSUE TITLE
Documentation - Clarify how to use tools

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-langchain4j#30]
The documentation makes all the concepts extremely clear and, really, for the most part, you don't need to read anything else than our doc to get set up (congrats on that!).

There's something a bit obscure though: how will the AI services call tools and how you should define your tools so that your AI services can actually make use of them.

For instance, let's take this example of the doc:
https://github.com/quarkiverse/quarkus-langchain4j/blob/a8ca184463219984acbf1db7e822feac3f1d20e9/docs/modules/ROOT/pages/ai-services.adoc?plain=1#L223-L234

- How is the `id` parameter linked to the `customerId` mention in the tool description?
- What will actually trigger the call to this particular tool?

Note that it might be a pretty stupid question for people having knowledge of all this but, given the rest of the doc is extremely useful to understand all the concepts, I was kinda hoping we could also describe how this would work.

**Comment by geoand** [comment]
Yeah, this makes perfect sense. 

I need to explain the algorithm.
