### ISSUE TITLE
Use Testcontainers modules for Milvus and ChromaDB

### ISSUE THREAD

**Issue by eddumelendez** [quarkiverse/quarkus-langchain4j#329]
Testcontainers 1.19.6 has released new modules for Vector Databases that are currently used in this project

- [Milvus](https://github.com/quarkiverse/quarkus-langchain4j/blob/main/milvus/deployment/src/main/java/io/quarkiverse/langchain4j/milvus/MilvusDevServicesProcessor.java#L395-L491)
- [ChromaDB](https://github.com/quarkiverse/quarkus-langchain4j/blob/main/chroma/deployment/src/main/java/io/quarkiverse/langchain4j/chroma/deployment/ChromaDevServicesProcessor.java#L234)

Benefits:
- It provides reliable wait strategies to start the service
- Milvus is configured with an embedded Etcd and local storage. But, it also allow to register an external Etcd and switch to minio storage via env vars.

Testcontainers modules
- https://java.testcontainers.org/modules/chromadb/
- https://java.testcontainers.org/modules/milvus/

**Comment by geoand** [comment]
That's awesome!
Thanks for the heads up 

@jmartisk would you like to add support for them?

**Comment by jmartisk** [comment]
We currently have a custom impl for Milvus where we run etcd/minio as separate containers and it's quite complicated. So yeah, this could make things simpler and maybe also faster. I'll give it a look when I get some time

**Comment by jmartisk** [comment]
And yeah, of course, it will have to wait until Quarkus actually upgrades to testcontainers 1.19.6 (https://github.com/quarkusio/quarkus/pull/38973)

**Comment by geoand** [comment]
Seems like that PR needs to be closed and redone manually as the docker-java version does not match

**Comment by jmartisk** [comment]
Will do

**Comment by geoand** [comment]
🙏🏼

**Comment by geoand** [comment]
We have now moved up to `1.19.7` in `main` 😉

**Comment by jmartisk** [comment]
Yeah but in Quarkus main, right? We haven't upgraded this repo to any Quarkus version with it (I don't think there is any such released version)

**Comment by geoand** [comment]
Yup, it was a heads up
