### ISSUE TITLE
Model gpt-4-vision-preview

### ISSUE THREAD

**Issue by lpedrov** [quarkiverse/quarkus-langchain4j#333]
When trying to use the gpt-4-vision-preview model in the following way:

```java
public void similarity() {
        final UserMessage userMessage = UserMessage.from("Describe the image",
                "https://79407da7c96c2b093a5ce0c99d874626.r2.cloudflarestorage.com/image");
        final ChatCompletionRequest chatCompletionRequest =
                ChatCompletionRequest.builder().model("gpt-4-vision-preview").messages(List.of(userMessage)).build();

        final QuarkusOpenAiClient quarkusOpenAiClient =
                new QuarkusOpenAiClient("<openai-api-key>");
        final ChatCompletionResponse chatCompletionResponse =
                quarkusOpenAiClient.chatCompletion(chatCompletionRequest).execute();

        Log.infov("response: {0}", chatCompletionResponse.choices().getFirst().message().content());
    }
```

I got the error:

```
jakarta.ws.rs.ProcessingException: No serializer found for class dev.ai4j.openai4j.chat.Content and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: dev.ai4j.openai4j.chat.ChatCompletionRequest["messages"]->java.util.Collections$UnmodifiableRandomAccessList[0]->dev.ai4j.openai4j.chat.UserMessage["content"]->java.util.ArrayList[0])
```

Could it be a bug or am I not doing things correctly?

Regards.

**Comment by geoand** [comment]
Could you give https://github.com/quarkiverse/quarkus-langchain4j/pull/334 a try?

**Comment by lpedrov** [comment]
> Could you give #334 a try?

Now I'm getting another error:

` jakarta.ws.rs.ProcessingException: No serializer found for class dev.ai4j.openai4j.chat.ImageUrl and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: dev.ai4j.openai4j.chat.ChatCompletionRequest["messages"]->java.util.Collections$UnmodifiableRandomAccessList[0]->dev.ai4j.openai4j.chat.UserMessage["content"]->java.util.ArrayList[1]->dev.ai4j.openai4j.chat.Content["image_url"])
`

**Comment by geoand** [comment]
Another try please?

**Comment by lpedrov** [comment]
> Another try please with the updated code?

Now I'm not sure if it could be a problem on my part!

I'm getting:

`dev.ai4j.openai4j.OpenAiHttpException: {
  "error": {
    "message": "Invalid chat format. Content blocks are expected to be either text or image_url type.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
`

**Comment by geoand** [comment]
Can you share the application you are using so I can try it myself?

**Comment by lpedrov** [comment]
> Can you share the application you are using so I can try it myself?

I just made a small class that I can share.

`import dev.ai4j.openai4j.chat.ChatCompletionRequest;
import dev.ai4j.openai4j.chat.ChatCompletionResponse;
import dev.ai4j.openai4j.chat.UserMessage;
import io.quarkiverse.langchain4j.openai.QuarkusOpenAiClient;
import io.quarkus.logging.Log;
import jakarta.enterprise.context.ApplicationScoped;

import java.util.List;

@ApplicationScoped
public class SimilarityService {

    public void similarity() {
        final UserMessage userMessage = UserMessage.from("Describe the image",
                "<an image url>");
        final ChatCompletionRequest chatCompletionRequest =
                ChatCompletionRequest.builder().model("gpt-4-vision-preview").messages(List.of(userMessage)).build();

        final QuarkusOpenAiClient quarkusOpenAiClient =
                new QuarkusOpenAiClient("<my-openai-api-key>");
        final ChatCompletionResponse chatCompletionResponse =
                quarkusOpenAiClient.chatCompletion(chatCompletionRequest).execute();

        Log.infov("response: {0}", chatCompletionResponse.choices().getFirst().message().content());
    }
}`

I'm using java 21 and quarkus version 3.7.3.

By the way, is possible to use @UserMessage to prompt this model (gpt-4-vision-preview)?

**Comment by geoand** [comment]
@langchain4j is the code above valid?

I see OpenAi responding with

```json
{
  "error": {
    "message": "Invalid chat format. Content blocks are expected to be either text or image_url type.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

**Comment by lpedrov** [comment]
> @langchain4j is the code above valid?
> 
> I see OpenAi responding with
> 
> ```json
> {
>   "error": {
>     "message": "Invalid chat format. Content blocks are expected to be either text or image_url type.",
>     "type": "invalid_request_error",
>     "param": null,
>     "code": null
>   }
> }
> ```

I'm not quite sure but the generated json has the "type" in uppercase. I made a quick test using python and with the "type" in uppercase also fails.

**Comment by langchain4j** [comment]
@lpedrov could you please enable logging and show the raw request sent to OpenAI?

**Comment by langchain4j** [comment]
Here is an example of how image should be provided inside the `UserMessage`: https://github.com/langchain4j/langchain4j-examples/blob/10d96a93097e87189deff323a48971bde8d22ade/open-ai-examples/src/main/java/OpenAiChatModelExamples.java#L37

**Comment by langchain4j** [comment]
`UserMessage.from("Describe the image", "<an image url>")` is a wrong way to do that, first argument is the `name`, second in the `text`:
```java
    /**
     * Create a {@link UserMessage} from a name and a text.
     * @param name the name.
     * @param text the text.
     * @return the {@link UserMessage}.
     */
    public static UserMessage from(String name, String text) {
        return new UserMessage(name, text);
    }
```

**Comment by lpedrov** [comment]
> `UserMessage.from("Describe the image", "<an image url>")` is a wrong way to do that, first argument is the `name`, second in the `text`:
> 
> ```java
>     /**
>      * Create a {@link UserMessage} from a name and a text.
>      * @param name the name.
>      * @param text the text.
>      * @return the {@link UserMessage}.
>      */
>     public static UserMessage from(String name, String text) {
>         return new UserMessage(name, text);
>     }
> ```

I'm using:

```java
public static UserMessage from(String text, String... imageUrls) {
        return UserMessage.builder()
                .addText(text)
                .addImageUrls(imageUrls)
                .build();
    }
 ```
    
 from  dev.ai4j.openai4j.chat. 
  
  So, this ```UserMessage.from("Describe the image", "<an image url>")``` is correct.

**Comment by lpedrov** [comment]
> @lpedrov could you please enable logging and show the raw request sent to OpenAI?

```json
{"model":"gpt-4-vision-preview","messages":[{"role":"user","content":[{"type":"TEXT","text":"Describe the images"},{"type":"IMAGE_URL","image_url":{"url":"image2"}}]}]}
```

As I said earlier the type field value in uppercase is causing the error.

**Comment by geoand** [comment]
Okay, I'll have a look tomorrow

**Comment by langchain4j** [comment]
Pardon, I missed that you are using openai4j directly... But why?

**Comment by lpedrov** [comment]
> Pardon, I missed that you are using openai4j directly... But why?

I need to use the "gpt-4-vision-preview" model for image analysis. I made some tests without using the specific json structure for the model, and the results were not satisfactory. I'm unsure if it's possible to create this specific type of prompt for this model using the @UserMessage annotation. The examples are not plentiful and the documentation is also scarce, so I opted to do it programmatically and since I'm using Quarkus, I prefer not to use third-party libraries. However, if there's another way, I would appreciate any help in that regard.

**Comment by geoand** [comment]
https://github.com/quarkiverse/quarkus-langchain4j/pull/334 has been updated and now works properly

**Comment by langchain4j** [comment]
@lpedrov providing images in `@UserMessage` is not possible yet, but you can use `UserMessage` objects with `ChatLanguageModel` interface, [here](https://github.com/langchain4j/langchain4j-examples/blob/10d96a93097e87189deff323a48971bde8d22ade/open-ai-examples/src/main/java/OpenAiChatModelExamples.java#L37) is an example.

**Comment by lpedrov** [comment]
> #334 has been updated and now works properly

Thank you @geoand. Do you have any idea when it will be released?

**Comment by geoand** [comment]
Maybe tomorrow or early next week

**Comment by lpedrov** [comment]
> openai4j
@langchain4j thank you.
But I am using the QuarkusOpenAiClient, and therefore, the openai4j is inherent. As I'm using quarkus, I want to keep the focus on quarkus libraries. Besides, it provides me with asynchronous calls, although I don't like the SyncOrAsyncOrStreaming that mixes 3 concepts in just one method, I would prefer a more reactive quarkus style, that is, returning a Uni.
