### ISSUE TITLE
Add pinecone embedding store

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#36]
[Pinecone](https://www.pinecone.io/) seems be to pretty popular with LangChain users so we should support it.

A java client [exists](https://github.com/pinecone-io/pinecone-java-client) and is based on gRPC, so I would like @cescoffier's input on how we should handle this

**Comment by cescoffier** [comment]
Yes, it would be great to have pinecone support. Do you know if they ship their Protobuf file?

**Comment by geoand** [comment]
[This](https://github.com/pinecone-io/pinecone-java-client/blob/main/src/main/proto/vector_service.proto) seems to be it, no?

**Comment by geoand** [comment]
The problem is that if we do this on our own, we essentially need to rewrite the pinecone client. As we sure we want to do that?

**Comment by cescoffier** [comment]
We would need to check how the "official" client handles gRPC. I would recommend using the Quarkus gRPC client to get all the metrics and other stuff. 

Now, I do not know the complexity. Is it just about calling the gRPC service, or is there other stuff?

**Comment by geoand** [comment]
It does look pretty straightforward honestly, no real logic involved, so in that case, I'll have a look on Monday (since I'm mostly off tomorrow)

**Comment by jmartisk** [comment]
I talked to @geoand and I'm picking this up, and by the way, they also have a REST api, so let's use that instead of gRPC.

**Comment by jmartisk** [comment]
Yes it should :) feel free to open a PR to change it, else I'll do it tomorrow.
I'm closing this issue because the Pinecone store is already implemented.
