### ISSUE TITLE
Upgrade to Quarkus 3.9

### ISSUE THREAD

**Issue by karesti** [quarkiverse/quarkus-langchain4j#377]
CR1 is out

**Comment by geoand** [comment]
We are **not** going to bump the Quarkus version of the extension as it results in the tooling not showing the extensions for older Quarkus versions

**Comment by jmartisk** [comment]
But we do want to upgrade at some point, right? We need to consume newer dependencies from newer Quarkus versions, for example, the testcontainers upgrade to fix https://github.com/quarkiverse/quarkus-langchain4j/issues/329. What's the usual strategy?

**Comment by geoand** [comment]
If it's just the `testcontainers` version bump, we can probably do the change in Quarkus LTS

**Comment by geoand** [comment]
I should note that we **can** and **should** bump this extension to Quarkus 3.8, but no further

**Comment by jmartisk** [comment]
Ah, I forgot I'd upgraded testcontainers in Quarkus 3.8.x already, so that wasn't a good example.
So, we could now upgrade to Quarkus 3.8.2?

**Comment by geoand** [comment]
> So, we could now upgrade to Quarkus 3.8.2?

Yes, free to do so

**Comment by jmartisk** [comment]
ok; https://github.com/quarkiverse/quarkus-langchain4j/pull/378

**Comment by jmartisk** [comment]
Hmm, but what will happen to Infinispan, we declare 15 in our pom, but Quarkus 3.8 contains 14. That probably will cause compatibility problems

**Comment by geoand** [comment]
If there are API changes, we're bound to run into problems at runtime.

**Comment by karesti** [comment]
Users can't use 14.0 in the server for this use case. The extension code for 14.0 works without any change for 15.0 in JVM mode. Native mode however, I had to change a couple of things to work with 15.0 upstream. I can state this as a limitation.
That, or I override the extension version here only for Infinispan if that's possible

**Comment by karesti** [comment]
What I mention above would be temporary, until we can upgrade fully to the next LTS. Since this extension is not in any LTS cycle, is it something that could be done ?

**Comment by karesti** [comment]
people who want to use newer versions of Quarkus, won't be able to use this extension neither

**Comment by geoand** [comment]
> What I mention above would be temporary, until we can upgrade fully to the next LTS. Since this extension is not in any LTS cycle, is it something that could be done ?

@gastaldi can only `quarkus-langchain4j-infinispan` depend on Quarkus 3.9 while the rest of the project depends on 3.8?

**Comment by gastaldi** [comment]
I believe so, yes. This information is stored in the extension metadata if I am not mistaken
