### ISSUE TITLE
ollama devservice still pulling orca-mini even if configured otherwise

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-langchain4j#381]
I have

```xml
    <dependency>
      <groupId>io.quarkiverse.langchain4j</groupId>
      <artifactId>quarkus-langchain4j-ollama</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkiverse.langchain4j</groupId>
      <artifactId>quarkus-langchain4j-ollama-devservices</artifactId>
    </dependency>
```

and then

```properties
quarkus.langchain4j.ollama.chat-model.model-id=mistral
quarkus.langchain4j.ollama.devservices.model=mistral
```

But yet when I start the application I see

```
14:23:23 INFO  [tc.ollama/ollama:latest] (docker-java-stream--63910882) Starting to pull image
14:23:23 INFO  [tc.ollama/ollama:latest] (docker-java-stream--63910882) Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)


--
Ollama Dev Services Starting: 14:25:33 INFO  [io.qu.la.ol.de.OllamaContainer] (build-44) Start pulling the 'orca-mini' model (3GB) ... would take several minutes ...
Ollama Dev Services Starting: 14:24:05 INFO  [io.qu.la.ol.de.OllamaContainer] (build-55) orca-mini pulling competed!
```

**Comment by geoand** [comment]
Have you tried to debug it and see what's going on?

**Comment by edeandrea** [comment]
I have not spent much time on it. One thing that seems odd to me though is that the dev service is split into a separate dependency. I've never seen that. Usually if an extension provides a dev service, the dev service is just part of the extension's deployment module.

Any idea why this is split out?

**Comment by geoand** [comment]
It was done because downloading the model takes forever.

I have heard a few complaints about this and what I can say is that we will certainly revisit the whole thing soon

**Comment by edeandrea** [comment]
> It was done because downloading the model takes forever.

Disable the devservice by default so that they have to enable it :)

**Comment by geoand** [comment]
It's under consideration

**Comment by vietk** [comment]
Hello, 
I just it' s just a display issue, I am using ollama with mistral, I saw the same logs but in the container the pull command contains the correct model 

<img width="556" alt="image" src="https://github.com/quarkiverse/quarkus-langchain4j/assets/1568850/0228ab18-6507-494c-863a-2644ae4b1705">

**Comment by vietk** [comment]
> I have heard a few complaints about this and what I can say is that we will certainly revisit the whole thing soon

Yes pulling the model is done in background once the ollama container has been started up. A model image is generally ~= 4GB so it can take some time.
To workaround I've build docker images with the model inside, but then you have to maintain the images

**Comment by vietk** [comment]
anyway to persist a container image from a dev service :D

**Comment by geoand** [comment]
I accidentally pushed the fix straight to main 🤦🏼

**Comment by edeandrea** [comment]
https://testcontainers.com/desktop/docs/#manage-the-lifecycle-of-containers
