### ISSUE TITLE
The extension adds vertx as dependency making CLI apps fails

### ISSUE THREAD

**Issue by lordofthejars** [quarkiverse/quarkus-langchain4j#389]
The extension adds vertx as a dependency, making CLI apps behaves incorrectly when starting as it detects the app as a web application instead of CLI application, and if port 8080 is used then it fails.

This blocks any Quarkus CLI tool that wants to use this extension.

**Comment by lordofthejars** [comment]
Also affects the dev mode as it detects as a web app instead of cli app.

**Comment by geoand** [comment]
I can't reproduce this (see for example [this](https://github.com/quarkiverse/quarkus-langchain4j/tree/main/samples/cli-translator)) sample CLI application.

As with #383, I believe there is something wrong with your setup

**Comment by jmartisk** [comment]
As far as I know, we add the vertx-http dependency only (?) because of the Dev UI functionality. 
But perhaps we could do without it, somehow

**Comment by lordofthejars** [comment]
https://github.com/lordofthejars/quarkus-langchain-examples/tree/main/booking-example-playwright

**Comment by jmartisk** [comment]
Yeah I think switching from `quarkus-vertx-http` to just `quarkus-vertx` is possible and would help. Furthermore we seem to only have that because of the usage of JSON stuff from the `io.vertx.core.json` package, so it wouldn't be hard to get rid of it completely if needed.

**Comment by lordofthejars** [comment]
Or for example go to the app and run quarkus dev. You'll see that it doesn't behave like a cli app but enables the web logic.

**Comment by jmartisk** [comment]
I've submitted https://github.com/quarkiverse/quarkus-langchain4j/pull/390, please check it @lordofthejars

**Comment by lordofthejars** [comment]
Oh nice, yes, it looks good; when a new release is published, I will try it for sure.
