### ISSUE TITLE
automatically use PGVector image when the extension is loaded

### ISSUE THREAD

**Issue by humcqc** [quarkiverse/quarkus-langchain4j#397]
When the extension : io.quarkiverse.langchain4j:quarkus-langchain4j-pgvector is included
datasource devservices should automatically use : pgvector/pgvector:pg16 image.

https://github.com/pgvector/pgvector/blob/master/README.md#docker

Perhaps we can update the [blog](https://docs.quarkiverse.io/quarkus-langchain4j/dev/pgvector-store.html) too to point to this image ?

**Comment by geoand** [comment]
Good point!

Would you like to do a Pull Request?

**Comment by humcqc** [comment]
why not! I will check how devservices works.

**Comment by geoand** [comment]
🙏

**Comment by humcqc** [comment]
I don't know how to change the blog, and for the moment i use pg16 image, there is no latest. There is a pg15 image. not sure which one quarkus recommand.

**Comment by geoand** [comment]
The docs (not a blog) are part of the repo under the `docs` directory

**Comment by humcqc** [comment]
ohhh, ok , done!
