### ISSUE TITLE
Introduce Anthropic module

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-langchain4j#413]
This will require work in the upstream LangChain4J project so we can introduce our own `AnthropicClient.Builder` (in the same way we do for Mistral & OpenAI).

**Comment by edeandrea** [comment]
langchain4j/langchain4j#834 has been opened for upstream work.

**Comment by geoand** [comment]
We have now moved to LangChain4j 0.29.1 which includes your [change](https://github.com/langchain4j/langchain4j/pull/834) that will enable this

**Comment by edeandrea** [comment]
Sounds good. I'll try to get to this next week.

**Comment by edeandrea** [comment]
I started working on this and then realized I missed something in langchain4j/langchain4j#834. I'll keep working, but I'll need langchain4j/langchain4j#873 before I can complete it.

**Comment by edeandrea** [comment]
I'm at a place now where I am blocked by langchain4j/langchain4j#873. I built langchain4j locally with that PR and ran all my code & tests against it locally and can verify that what I have works.
