### ISSUE TITLE
EasyRAG sample doesn't work with tesseract

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#418]
It seems like when Tesseract is installed, Tika seems to lose some context or something, as we get:

```
Caused by: org.apache.tika.exception.TikaException: TesseractOCRParser bad exit value 1 err msg: Tesseract Open Source OCR Engine v4.1.1 with Leptonica
Error in fopenReadStream: file not found
Error in pixRead: image file not found: The "Standard savings account" offers a first-time savers and those with low balances a hassle-free way to save.
Image file The "Standard savings account" offers a first-time savers and those with low balances a hassle-free way to save. cannot be read!
Error during processing.
```

This indicates that the text file (named `standard-saving-account.txt`) is not being parsed correctly

**Comment by geoand** [comment]
@jmartisk @sberyozkin any idea what's going on?

cc @dandreadis who first found this issue

**Comment by jmartisk** [comment]
I was just about to report the same.
This is super mega weird, I could swear that it worked for me yesterday, and then suddenly it stopped working.

**Comment by dandreadis** [comment]
I haven't quite understood how is this supposed to work: when installed, does it take over for all types of document parsing, or just specific ones? In my system, with that in place it parsed 2 out of the 4 files. (also produced multi line warnings).

**Comment by jmartisk** [comment]
Yeah I now also get just 2 files parsed successfully. I absolutely don't understand why it worked for me yesterday and what has changed since then. 
Even weirder, we have `EasyRagTest` in place that depends on being able to parse a PDF file, and the test passes, but with the `chatbot-easy-rag` application, PDF fails.

**Comment by geoand** [comment]
My guess is that it works properly only if the image is parsed last

**Comment by jmartisk** [comment]
Seems like it has problems with png images, when I convert it to jpg, it seems to work.

**Comment by jmartisk** [comment]
Let's just convert the `retirement-money-market.png` file to jpg for now, hm?

**Comment by geoand** [comment]
Sure yeah

**Comment by dandreadis** [comment]
When I tried it manually (using the command line) it correctly extracted the text from the .png.
