### ISSUE TITLE
Eliminate `BeanXProviderSupplier`

### ISSUE THREAD

**Issue by cescoffier** [quarkiverse/quarkus-langchain4j#43]
Discovering this value is hard. Adding the implementation class name might be simpler.

**Comment by cescoffier** [comment]
I believe it would be simpler if the user can just write:

```
@RegisterAiService(retriever=TheClassNameOfMyBean.class)
```

**Comment by geoand** [comment]
I'll have a look at this tomorrow hopefully.

**Comment by geoand** [comment]
I was thinking of this, and I have a new proposal:

What if we keep what we have now, but change the default to something like: `BeanIfExistsChatMemoryProviderSupplier` which would automatically use the bean if it exists, but would not fail it no bean exists and would just not use any memory.

**Comment by cescoffier** [comment]
That works!

The next issue is: what would be the value when you have multiple
retrievers and you want to select one. The retriever is not a supplier,
just a plain implementation of the retriever.

I think Suppliers are used as factories. However in our case, the scope is
what define when to create the instance.

**Comment by geoand** [comment]
> I think Suppliers are used as factories

Yeah, that was my intention. If users want more advanced ways of choosing an implementation, then it's up to them to write the supplier.

**Comment by geoand** [comment]
https://github.com/quarkiverse/quarkus-langchain4j/pull/51 should take care of it
