### ISSUE TITLE
Clear ChatMemory when AiService scope is closed

### ISSUE THREAD

**Issue by andreadimaio** [quarkiverse/quarkus-langchain4j#430]
I'm playing with the tools and during my testing I found the "clear chat memory" bevahior that happens when the AiService scope is closed. Looking at the documentation, there is a section about ChatMemory that says:
> The topic of ChatMemory cleanup is of paramount importance in order to avoid having the application terminate with out of memory errors. For this reason, the extension automatically removes all the ChatMemory objects from the underlying ChatMemoryStore when the AI Service goes out of scope (recall from our discussion about [[scope]](https://docs.quarkiverse.io/quarkus-langchain4j/dev/ai-services.html#scope) that such bean are @RequestScoped be default).

> However, in cases where more fine-grained control is needed (which is the case when the bean is declared as @Singleton or @ApplicationScoped) then io.quarkiverse.langchain4j.ChatMemoryRemover should be used to manually remove elements.

This is the code that runs during the clear operation in the QuarkusAiServiceContext class:
```java
    /**
     * This is called by the {@code close} method of AiServices registered with {@link RegisterAiService}
     * when the bean's scope is closed
     */
    public void close() {
        clearChatMemory();
    }

    private void clearChatMemory() {
        if (chatMemories != null) {
            chatMemories.forEach(new BiConsumer<>() {
                @Override
                public void accept(Object memoryId, ChatMemory chatMemory) {
                    chatMemory.clear();
                }
            });
            chatMemories = null;
        }
    }
```

Now, at today, if I use an AiService like below, and this interface is exposed by a rest service, if I run the same rest api twice, __with the same memory id__, the result will always be an empty chat memory, this is because MyAIService inherits the `@RequestScoped` and at the end of the request the chat memory is cleaned up.

```java
@RegisterAiService
interface MyAIService {
   @SystemMessage("This is a systemMessage")
   @UserMessage("{text}")
   String chat(@MemoryId String id, String text);
}
```
If instead the AIService is annotated as `@ApplicationScope` (as suggested in the documentation), everything works correctly.
I'm thinking about this behavior and I don't understand why this "clear operation" is needed, what I mean is, since the chat memory has a maximum size, why is there a need to clean it?

**Comment by andreadimaio** [comment]
If the goal is to clean up memory IDs (because they can grow), my thought is that it is more correct to leave the burden on the developer and not do it automatically.

**Comment by geoand** [comment]
> If the goal is to clean up memory IDs (because they can grow), my thought is that it is more correct to leave the burden on the developer and not do it automatically.

This is exactly the goal and I very much believe that what we do is a perfectly reasonable default

**Comment by andreadimaio** [comment]
Thanks for the answer, I'm going to close the issue.

**Comment by geoand** [comment]
👌
