### ISSUE TITLE
Use quarkus-websockets-next in samples

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#432]

**Comment by edeandrea** [comment]
I'm not sure that `quarkus-websockets-next` is fully baked yet. See https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/websockets-next and https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/websockets-next.3A.20more.20questions

**Comment by edeandrea** [comment]
Not sure if you might run into any of the issues described there?

**Comment by geoand** [comment]
I ran into 0️⃣ issues when I tried something similar to one of the samples we have and I kind of doubt there will be any problems as the samples use only the absolute basics of Websockets

**Comment by edeandrea** [comment]
Just thought I'd mention it because I did run into issues when I tried it out.

**Comment by geoand** [comment]
Appreciated, thanks!

**Comment by geoand** [comment]
> Just thought I'd mention it because I did run into issues when I tried it out (and from which I started from one of your samples :) ).

Which exact issues?

**Comment by edeandrea** [comment]
The ping/pong. Because everything is session scoped there is no way to broadcast a ping to all open connections.

**Comment by geoand** [comment]
I see. That shouldn't be relevant for our samples though

**Comment by edeandrea** [comment]
Maybe. Maybe not. If you have your browser up for more than 2 or 3 minutes without activity then the connection will eventually time out and you'll need to reload the browser, and if you aren't persisting the chat history, then the conversation will be lost

**Comment by geoand** [comment]
I would say we don't have to worry about that for these samples

**Comment by jmartisk** [comment]
Maybe add that as a separate property in the root pom.xml to have it centralized in one place?

**Comment by geoand** [comment]
I was thinking about that, but I am more leaning on making the samples entirely self contained as that makes it much easier for people to copy and paste them into their own projects

**Comment by jmartisk** [comment]
Right, we haven't quite resolved the discussion about how self-contained they should become. But it definitely makes sense to uncouple them at least a little.

**Comment by geoand** [comment]
I will uncouple them completely for now as that will be better than the current state.

If / when we have better ideas of how to improve, we can easily implement them.

**Comment by geoand** [comment]
https://github.com/quarkiverse/quarkus-langchain4j/pull/500 is what I have in mind
