### ISSUE TITLE
Add support for `fromResource` in `@SystemMessage` and `@UserMessage`

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#434]
@langchain4j I assume those attributes are stable and won't change, correct?

If so, this is a good time to add support for them :)

**Comment by langchain4j** [comment]
@geoand seems like it is "stable", but I am not sure this brings much value now, as we are thinking about adding a way to dynamically supply system/user message templates as lambdas/suppliers.

**Comment by langchain4j** [comment]
Can't find the original discussion, but here are some relevant ones:
https://github.com/langchain4j/langchain4j/pull/862
https://github.com/langchain4j/langchain4j/issues/785

**Comment by geoand** [comment]
🙏🏼
