### ISSUE TITLE
Streaming chat in DevUI

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#442]
Would it be possible to use a `StreamingChatModel` in the DevUI if it's accessible?
This would allow to stream the response back

**Comment by geoand** [comment]
@jmartisk do you think this is possible without too much work?

**Comment by jmartisk** [comment]
What would that mean exactly, that the response from the model is a Multi and we would forward the events from the Multi to the UI as they arrive, over a websocket?

**Comment by iocanel** [comment]
I can give it a shot.

**Comment by iocanel** [comment]
I have something is working. However, it will only work when rag is disabled (and it's true by default).

Should we add a message / alert to let the user know when streaming chat is not enabled and why it's not enabled?
Would you think that a vaadin alert or a console.log is more appropriate for this?

**Comment by geoand** [comment]
> Should we add a message / alert to let the user know when streaming chat is not enabled and why it's not enabled?

I think that's a good idea
