### ISSUE TITLE
Revamp ollama DevService

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#453]
The DevService currently uses Docker and is not terribly useful.

It would be better if we rebuilt this from scratch and simply delegated to the Ollama CLI

**Comment by geoand** [comment]
cc @cesc

**Comment by cescoffier** [comment]
Well, what if docker/podman is not installed? It's more or less the same problem.

We may want to keep the existing one (it's separated anyway), but we need a better story. 

Also (and that's where things are ticky), this new "ollama dev service" may not be bound to ollama. If I have a Mistral or llama2 model running somewhere behind an openai-like API, why can't I use this dev service locally?

**Comment by geoand** [comment]
> What if the CLI isn't installed

That's the point - we install it! It's quite easy and we do that already in other places in Quarkus

**Comment by geoand** [comment]
I'll close this in favor of #505 which already has a PR opened for it

**Comment by geoand** [comment]
> What if the CLI isn't installed? Isn't the main point of Dev Services to have stuff running OOTB without having to install anything?

See my updated thinking on this [here](https://github.com/quarkiverse/quarkus-langchain4j/discussions/505#discussioncomment-9233640).
