### ISSUE TITLE
Check if pg-vector from langchain4j can be used as is.

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#46]
We would probably however want a dev-service for this in any case

**Comment by sebastienblanc** [comment]
@geoand I would like to help on this one, your idea is to check if we can use directly https://github.com/langchain4j/langchain4j/blob/main/langchain4j-pgvector/src/main/java/dev/langchain4j/store/embedding/pgvector/PgVectorEmbeddingStore.java , correct ?

**Comment by geoand** [comment]
Hey @sebastienblanc,

Yeah, exactly!

**Comment by sebastienblanc** [comment]
At a first quick "brain" scan, maybe it can be used as is but it would be nice if we could pass it directly an existing Quarkus PG (eventually Reactive) datasource ...

**Comment by sboeckelmann** [comment]
@sebastienblanc Sorry this may seem a may be a bit off-topic.
As the maintainer of https://github.com/quarkiverse/quarkus-opensearch I am currently investigating on integrating https://github.com/langchain4j/langchain4j/blob/main/langchain4j-opensearch/src/main/java/dev/langchain4j/store/embedding/opensearch/OpenSearchEmbeddingStore.java.
Issue and pull request will follow 😄 

It seems to be a general issue with the langchain4j EmbeddingStore implementations:
They don't support the respective Datasources or Clients to be passed directly.

And rather than copying the code it would make sense to adjust them directly within the langchain4j project.
This would make it easier to support (all of) them in Quarkus.
What's your thought on this?

**Comment by geoand** [comment]
> At a first quick "brain" scan, maybe it can be used as is but it would be nice if we could pass it directly an existing Quarkus PG (eventually Reactive) datasource ...

For sure, we want to reuse the Quarkus PG stuff

**Comment by geoand** [comment]
> @sebastienblanc Sorry this may seem a may be a bit off-topic. As the maintainer of https://github.com/quarkiverse/quarkus-opensearch I am currently investigating on integrating https://github.com/langchain4j/langchain4j/blob/main/langchain4j-opensearch/src/main/java/dev/langchain4j/store/embedding/opensearch/OpenSearchEmbeddingStore.java. Issue and pull request will follow 😄
> 
> It seems to be a general issue with the langchain4j EmbeddingStore implementations: They don't support the respective Datasources or Clients to be passed directly.
> 
> And rather than copying the code it would make sense to adjust them directly within the langchain4j project. This would make it easier to support (all of) them in Quarkus. What's your thought on this?

👋🏼 

I can't speak for upstream langchain4j, but in this repository we defiinitely want to reuse all the Quarkus related datasources / clients stuff - see for example how the redis integration was done.

**Comment by sboeckelmann** [comment]
> I can't speak for upstream langchain4j, but in this repository we defiinitely want to reuse all the Quarkus related datasources / clients stuff - see for example how the redis integration was done.
👍 

My question is: 
Do we want to create and maintain our own EmbeddingStore implementations within quarkus-langchain4j or try to have the langchain4j implementations to take a more common approach by creating a merge request for passing the Datasource / Client?
 
From my point of view this project should decide upon on a preferred EmbeddingStore strategy, as both approaches are having their own pros and cons.

Shall I create an issue in upstream langchain4j for taking up this discussion over there? It probably doesn't make much sense to discuss this any further until we know more about the upstream project's perspective.

**Comment by geoand** [comment]
> Shall I create an issue in upstream langchain4j for taking up this discussion over there? 

Please do. If upsteam follows that approach, then it makes it super easy for us to use here. Otherwise, we'll need a custom implementation for this repo.

**Comment by sebastienblanc** [comment]
While we wait for maybe an upstream refactoring I started to play with adding the support, you can find the branch here, please have in mind that it's the first time ever I try to create an extension, I based it on how the Redis store was made : https://github.com/sebastienblanc/quarkus-langchain4j/tree/pgvector

You can also find a simple project that uses this store : https://github.com/sebastienblanc/pgvector-ingestor

**Comment by geoand** [comment]
Thanks!

@jmartisk wanna review this?

**Comment by jmartisk** [comment]
I'm sick, I can probably have a look later this week, but I don't mind if you don't wait for me

**Comment by jmartisk** [comment]
Hey @sebastienblanc I had a quick check, some notes:

- In my opinion the vector dimension should be a required property and we shouldn't magically assume 1536. Or, to be more precise, it should be required in case that we need to create the table (if it already exists then it's unnecessary to know the dimension?)
- I assume the extension itself can depend on the jdbc driver (`quarkus-jdbc-postgresql`) so the application doesn't have to add the dependency itself

I couldn't get it to work though. I am getting this while initializing the database
```
Caused by: org.postgresql.util.PSQLException: ERROR: could not open extension control file "/usr/share/postgresql/14/extension/vector.control": No such file or directory
```
Does this mean that the database has to be installed in the filesystem for this to work?? Meaning that initializing the db won't work remotely, or even when postgres is running in a container??

**Comment by sebastienblanc** [comment]
@jmartisk Hi ! Thanks for the quick check, and again, it's in draft mode ;) 
Good point on the dimension, it will remove the default and make it mandatory
For `quarkus-jdbc-postgresql` why not but I'd assumed that people would already be using it in their app and then add `quarkus-langchain4jpgvector` later.
That's a weird error that you are getting , I tested against a remote managed PG (on Aiven) , how did you test ?

**Comment by jmartisk** [comment]
>  For quarkus-jdbc-postgresql why not but I'd assumed that people would already be using it in their app and then add quarkus-langchain4jpgvector later.

Yeah but not in all cases. If the `pgvector` extension requires this to be usable, it should be in the dependencies :)

> That's a weird error that you are getting , I tested against a remote managed PG (on Aiven) , how did you test ?

I am using a DevServices instance (spawned by Quarkus in dev mode automatically)

**Comment by sebastienblanc** [comment]
Okay, let me try with DevServices

**Comment by gsmet** [comment]
There's a good chance you will need to run a `CREATE EXTENSION pgvector` (or similar) in the Dev Services (and I'm not completely sure if the extension is around by default or if you need something in the container).

**Comment by sebastienblanc** [comment]
`CREATE EXTENSION pgvector` is done by the extension already , I think it might be because of the testcontainer version, I'm reading this right now https://medium.com/mark-penaranda/testcontainers-with-custom-docker-image-in-jdbc-url-64655dcbf4cb

**Comment by sebastienblanc** [comment]
Ok I can reproduce the problem , by adding to my app properties `quarkus.datasource.devservices.image-name=ankane/pgvector:v0.5.1` it works. 
Now I'm not sure what is the way to solve this, add this property to the extension or document it ?

**Comment by sebastienblanc** [comment]
Something like
https://github.com/sebastienblanc/quarkus-langchain4j/commit/2f23aeda86597cd372e3fd5b63177e8d4b6619d2
?

**Comment by jmartisk** [comment]
Yeah, only - is there a way to be more sure from the thrown exception that the reason is the missing module, and not something else? Just to make sure we don't swallow an exception that is about something else. Or at least print the exception details into stderr.

**Comment by sebastienblanc** [comment]
Good idea, I check now the exception message for the specific message related to the missing extension. 
Should I open a PR with my repo, so we can continue the discussion there ?

**Comment by jmartisk** [comment]
Yes please :)

**Comment by gsmet** [comment]
I wonder if we should have a build item that allows replacing a dev service image with another. That would makes things easier here.
Obviously not blocking for making progress here but maybe we should think about it.

**Comment by geoand** [comment]
That's a very good idea

**Comment by jmartisk** [comment]
This is resolved
