### ISSUE TITLE
Add feature to set settings per prompt

### ISSUE THREAD

**Issue by Plawn** [quarkiverse/quarkus-langchain4j#461]
Hello, 

I have service registering multiple prompts and I want to use different `temperature` and `top_p` settings for each prompt but there is no option to do this. Can this be added with an Annotation like `@Settings` or `@AiSettings` or `@PromptSettings` ?

Thanks

**Comment by geoand** [comment]
Hi,

Those are settings which apply per `ChatLanguageModel` (see `OpenAiChatModel`), which means they cannot be set per AiService.
What you can do is use `@RegisterAiService(modelName="foo")`

where you have configured something like:

```properties
quarkus.langchain4j.openai.foo.temperature=1.0
```

**Comment by Plawn** [comment]
Thanks for the quick response !

Oh I see, is there a point of on allowing it to be set in application.properties / yaml versus being in the code as annotation ?

**Comment by geoand** [comment]
The reason is that a `ChatLanguageModel` can serve multiple purposes, one of which is to back an AiService.

**Comment by Plawn** [comment]
thanks !

**Comment by geoand** [comment]
🙏🏼
