### ISSUE TITLE
Improve the csv-chatbot sample

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#472]
The csv-chatbot is mind-blowing because it demonstrates how the LLM can transform a user question into a query and then execute it in order to get a response.

I believe however that it can be improved to remove some rough edges:

* The system message currently contains the database schema which means it's hardcoded. I believe we can use Hibernate to get the schema for the Movie entity automatically.
* The code uses `DataSource` to execute the raw query whereas I believe things can be simplified by using `StatelessSession`

**Comment by jmartisk** [comment]
A StatelessSession works with entities, no? The reason I didn't use Hibernate for the retrieval (only for the initial import) is that you don't know what exactly the SQL query will ask for, and if the query asks for some aggregation data , foe example `count(*) as movie_count` then you can't unwrap an entity from the result.

**Comment by jmartisk** [comment]
So by requiring the result to be mappable to the `Movie` entity, you lose the possibility to ask questions like   "What is the average rating of movies in the database"

**Comment by geoand** [comment]
Good point.

I still believe however that there is a way to use Hibernate to do all these queries with some lower level API that is however better than DataSource + Connection + ResultSet which are sooooo outdated

**Comment by jmartisk** [comment]
As for

> The system message currently contains the database schema which means it's hardcoded. I believe we can use Hibernate to get the schema for the Movie entity automatically.

Ok you can get the schema, but how will it deduce some additional information about the columns? For example, it currently is quite important to add that `genre` is a comma-separated list, so that the LLM can generate proper queries for it. Can this be added to the database schema as some sort of text description for columns?

**Comment by geoand** [comment]
I have not dug into it yet (I plan to look into it next week).

My main point is writing and maintaining this system message by hand should not be necessary

**Comment by geoand** [comment]
@zbendhiba had an example of using Camel for ingestion which was really interesting, so there could be multiple ways to improve this sample

**Comment by geoand** [comment]
Right, I'm undecided on that one which is why my PR doesn't make any change to that

**Comment by langchain4j** [comment]
> Ok you can get the schema, but how will it deduce some additional information about the columns? For example, it currently is quite important to add that genre is a comma-separated list, so that the LLM can generate proper queries for it. Can this be added to the database schema as some sort of text description for columns?

One of the options is to provide a few (random?) rows of data to the LLM, so that it knows how it looks like.
