### ISSUE TITLE
Easy RAG: strategies to control whether data should be ingested or not

### ISSUE THREAD

**Issue by jmartisk** [quarkiverse/quarkus-langchain4j#473]
When using the default (in-memory) embedding store, it is irrelevant, but when running against a persistent store, it is necessary to be able to avoid re-ingesting all data when the application is started multiple times against the same store.

This is relevant not exclusively to Easy RAG, but for Easy RAG it is most important, because the ingestion is executed automatically from extension code, not by any application code, so the user currently has no way to control it.

I propose introducing a property `quarkus.langchain4j.easy-rag.ingestion-strategy` with the following values:
- `on`: always ingest all documents from the data directory
- `if-empty` (default): ingest if the embedding store is detected to be empty
- `overwrite`: delete everything in the store and re-ingest (this is a little tricky because there is no unified `delete` operation in `dev.langchain4j.store.embedding.EmbeddingStore`, but we can provide it at least for some of our implementations)
- `off`: never ingest anything - assume that the embedding store is already populated

**Comment by jmartisk** [comment]
@langchain4j, or is there perhaps any common way that we should reuse here - how does one usually detect whether ingestion is necessary or the store is already populated?

**Comment by langchain4j** [comment]
@jmartisk there is nothing in langchain4j yet, but you can check out langchain and llamaindex, I am sure they have something.
I was thinking about an option to calculate a checksum of all documents and re-ingest them (or only the difference) if it changes.

**Comment by geoand** [comment]
> I was thinking about an option to calculate a checksum of all documents and re-ingest them (or only the difference) if it changes.

This would be awesome if we could do.

> I propose introducing a property quarkus.langchain4j.easy-rag.ingestion-strategy with the following values

This absolutely makes sense in the same way that Quarkus provides a configuration option for whether Hibernate should create the schema.
