### ISSUE TITLE
Support for Palm 2 LLM

### ISSUE THREAD

**Issue by silviu-negoita** [quarkiverse/quarkus-langchain4j#476]
Hello,

Can you add support for Google Palm 2?  

Thanks

**Comment by geoand** [comment]
I'll have a look next week!

Thanks

**Comment by geoand** [comment]
@langchain4j is this supported in LangChain4j?

**Comment by langchain4j** [comment]
@geoand yes, it is langchain4j-vertex-ai (without Gemini) module

**Comment by geoand** [comment]
Gotcha, thanks!

**Comment by geoand** [comment]
@silviu-negoita is there any chance you could try #531?

**Comment by silviu-negoita** [comment]
> @silviu-negoita is there any chance you could try #531?

Yes, I will take a look if not next week, the week after since holidays are coming. Any idea when when it will be a release? If not, I will take it locally. 
Thanks for handling this

**Comment by geoand** [comment]
I will probably do a release sometime next week since there are a few more things I want to get in in the meantime
