### ISSUE TITLE
Allows injection of EmbeddingStore regardless of their type

### ISSUE THREAD

**Issue by cescoffier** [quarkiverse/quarkus-langchain4j#49]
It should be possible to inject EmbeddingStore:

```
@Inject EmbeddingStore store;
```

At the moment, it needs to be RedisEmbeddingStore or ChromaEmbeddingStore.
It is not homogeneous with the EmbeddingModel, which is injected as `@Inject EmbeddingModel model`  regardless of the implementation.

**Comment by geoand** [comment]
Good point!

It should be easy to fix.

**Comment by geoand** [comment]
https://github.com/quarkiverse/quarkus-langchain4j/pull/52 fixes the issue
