### ISSUE TITLE
Missing guides links

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-langchain4j#535]
The extensions are missing the guides links in their metadata. We could do one blanket link to https://docs.quarkiverse.io/quarkus-langchain4j/dev/index.html in each extension, or we could provide some links that drill down to specifics, for the individual services extensions. 

The symptom of this is that https://quarkus.io/extensions/io.quarkiverse.langchain4j/quarkus-langchain4j-core/ (for example) doesn't link to any docs.

**Comment by geoand** [comment]
I think we can probably just link to the index for now
