### ISSUE TITLE
:grey_question: (SYSTEM) PROMPT as external configuration

### ISSUE THREAD

**Issue by adriens** [quarkiverse/quarkus-langchain4j#540]
#  :information_source:  Context

We are bulding an agent for our division, its aim is to answer incoming questions so we don't have to. 

We have currently working on the Quarkus/podman/ollama stack.

I would like to share the same SYSTEM PROMPT accross all our functions to provide an homogeneous UX for people asking questions.

eg : 

> You are the assisstant of GLIA division, your mission is to....

We have started to implement some functions and I wonder how we could inject SYSTEM prompt from within standard conf files so we can use it in very wide amount of places in our code and : 

- Avoid code duplication
- Split PROMPT conf vs. real code

# :grey_question: Question

- Would you share some code on how to parametrize SYSTEM prompt thanks to external/injected configuration

**Comment by geoand** [comment]
Hi,

It seems to me that `@SystemMessage(fromResource="someresource")` is what you are after.

**Comment by adriens** [comment]
> Hi,
> 
> It seems to me that `@SystemMessage(fromResource="someresource")` is what you are after.

Looks like, yes, do there is some example in the samples ?

**Comment by geoand** [comment]
There are tests that use it, but I am not in front of my machine now so it's hard to find them.

I can look later

**Comment by adriens** [comment]
No worry, that's very cool to get these elements :pray:

**Comment by geoand** [comment]
[This](https://github.com/quarkiverse/quarkus-langchain4j/blob/0.12.1/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java#L407) is an example usage in our testsuite

**Comment by adriens** [comment]
Es ist wirklich gut, vielen danke für die hefle : 

```java
    interface Translator {

        @SystemMessage(fromResource = "messages/translate-system")
        @UserMessage(fromResource = "/messages/translate-user.txt")
        String translate(@V("text") String text, @V("lang") String language);
    }
```
