### ISSUE TITLE
:grey_question: How to RAG on Neo4J

### ISSUE THREAD

**Issue by adriens** [quarkiverse/quarkus-langchain4j#542]
# :grey_question: Context

From Python/LlamaIndex and Python/Langchain I could successfully interact with a Neo4J instance : 

- [🇺🇳 Discover a country UN SDGs concerns w/ Open Metadata on Neo4J](https://dev.to/adriens/discover-a-country-un-sdgs-concerns-w-open-metadata-on-neo4j-13df)
- [With Lanchain](https://youtu.be/aVzsrGGk4K0?si=ZnLB7xTw7v9EXe2i&t=723)
- [With LlamaIndex](https://youtu.be/aVzsrGGk4K0?si=xyP_ckyfq00BvdHa&t=917)

Now, I would like to use this on Quarkus for a corporate KG and I wonder how this could be achieved on the Quarkus stack.

# :grey_question: Question

- Considering an input Neo4J configuration, show how to do RAG on it with Langchain4J and package the whole thing within Quarkus.

**Comment by geoand** [comment]
We don't yet have a Neo4j based embedding store, but it should not be hard to add one (especially since there is a Quarkiverse extension for Neo4j).

cc @jmartisk

**Comment by adriens** [comment]
> We don't yet have a Neo4j based embedding store,

It would be partial embeddings, but also `text2cypher` as it should be able to use the schema to tranform the incoming question into a proper cypher query isn't it ?

**Comment by geoand** [comment]
That's a separate concern IMO

**Comment by adriens** [comment]
So here we should focus on the embedding, not the text2cypher : right ?

**Comment by geoand** [comment]
Indeed

**Comment by adriens** [comment]
Should I let this issue opened then ?

**Comment by geoand** [comment]
Yup

**Comment by jmartisk** [comment]
There's a neo4j embedding store in langchain4j upstream and it uses the same client as the quarkus-neo4j extension, so it should be possible to integrate here. Yeah I can look into it, unless somebody else is super eager to do this

**Comment by adriens** [comment]
That would be really awesome. I'll can provide you feedback while implemented as we are currently building a projetc on top of both QUarkus & Neo4J. :star_struck: :nerd_face:

**Comment by jmartisk** [comment]
Resolved via https://github.com/quarkiverse/quarkus-langchain4j/pull/548

**Comment by adriens** [comment]
Thanks a lot guys. I'll keep the community up-to-date.
**:information_source:  We'll use this, it's still a work in progress, I'll embed this for a Call For Paper, which uses this extension**

**Comment by geoand** [comment]
🥳

**Comment by adriens** [comment]
- https://github.com/quarkiverse/quarkus-langchain4j/pull/548
