### ISSUE TITLE
Use progress bars on other pages beyond Chat

### ISSUE THREAD

**Issue by jmartisk** [quarkiverse/quarkus-langchain4j#554]
The chat Dev UI page shows a progress bar when you submit a message to make it clear that the user has to wait a while. We could add this to the other pages too

**Comment by iocanel** [comment]
@jmartisk would you mind being a little more specific on which are the other areas you are referring too. I went through the samples and it seems that all samples that feature a web UI do have progress bars.

**Comment by jmartisk** [comment]
Maybe it's just the Embedding store page that doesn't have it right now
