### ISSUE TITLE
Fraud detection by distance is broken

### ISSUE THREAD

**Issue by iocanel** [quarkiverse/quarkus-langchain4j#567]
While working on #566 I realized that our distance based fraud detection is broken.
By broken I mean that it constantly calculates as 0 the distance between any pair of cities and thus fails to correctly detect frauds.

I think that the issue has to do with the capabilities of the model. ChatGPT 4 is capable to calculate distances, while 3.5 is not.

**Comment by geoand** [comment]
In that case, we should probably use the latest OpenAI model

**Comment by iocanel** [comment]
I verify, that going with gpt-4 solves, the issue. I am working on a PR.

**Comment by iocanel** [comment]
Resolved as of #568
