### ISSUE TITLE
Document how to use Podman Desktop (AI Studio)

### ISSUE THREAD

**Issue by cescoffier** [quarkiverse/quarkus-langchain4j#577]
Document how one can use Podman Desktop to serve models locally. 

Here is what I used:

- Pull the model in Podman Desktop AI Studio and create a service (Note the port number)
- Configure the openai extension as follow:

```properties
# Configure the port accordingly
quarkus.langchain4j.openai.base-url=http://localhost:53977/v1
# Might be a bit slow (~20s for my M1)
quarkus.langchain4j.openai.timeout=60s

quarkus.langchain4j.openai.chat-model.temperature=0.8

quarkus.langchain4j.openai.log-requests=true
quarkus.langchain4j.openai.log-responses=true
```

Note the that `model-id/name`  is ignored. Podman Desktop AI services serve a single model. Typically, I'm currently using `Granite-7B`.

**Comment by geoand** [comment]
And I assume that Podman Desktop AI does not yet support GPU inference? 

Also, do we know what they running as the serving layer?

**Comment by cescoffier** [comment]
No, unfortunately no GPU yet.

Under the hood, it's llama.cpp, as for 80% of the local model serving tools :-)

**Comment by geoand** [comment]
Thanks!
