### ISSUE TITLE
It should be possible to specify the seed when generating images.

### ISSUE THREAD

**Issue by iocanel** [quarkiverse/quarkus-langchain4j#580]
This may be applicable to other areas too, but I think that its a must for images, as generating images is an iterative process that requires a lot of tuning in the prompt and being able to use a fixed seed is really important.

**Comment by geoand** [comment]
👌

**Comment by iocanel** [comment]
@langchain4j with a quick glimpse on OpenAI, I don't see any way to set this. Is it even exposed by their API ?. If not, I guess there is not much we can do.

**Comment by langchain4j** [comment]
Seed can be specified only for chats, image generation API does not have this option: https://platform.openai.com/docs/api-reference/images

**Comment by iocanel** [comment]
Thanks @langchain4j. I'll close then and we can revisit, if seed ever becomes available.
