### ISSUE TITLE
Explore adding Open WebUI to the DevUI when using Ollama

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#581]
I see [Open WebUI](https://github.com/open-webui/open-webui) being mentioned a lot in the context of Ollama.

We should look into adding it to the WebUI (probably via it's [Docker option](https://docs.openwebui.com/getting-started/#quick-start-with-docker-)).

**Comment by iocanel** [comment]
Do you see it as a new extension or something that would be triggered when OpenAI and Ollama extensions are used ?
Also, would you wire it as a Dev Service or you'd explicitly start it from the Dev UI? In the later case is there an existing extension doing something similar ?

**Comment by geoand** [comment]
> Do you see it as a new extension or something that would be triggered when OpenAI and Ollama extensions are used ?

The latter

> Also, would you wire it as a Dev Service or you'd explicitly start it from the Dev UI

Again the latter :)

**Comment by phillip-kruger** [comment]
Nothing that I know about. But it should be easy enough.
