### ISSUE TITLE
WebSearchTool breaks the DevUI

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#652]
Chatting with the model in `0.15.0` is no longer possible, but instead we get:

```
{"id":12,"error":{"code":-32603,"message":"Method [io.quarkiverse.langchain4j.quarkus-langchain4j-core.chat] failed: No bean found for required type [class dev.langchain4j.web.search.WebSearchTool] and qualifiers [[]]"},"jsonrpc":"2.0"}
```

The reason this happens is because LangChain4j now includes `dev.langchain4j.web.search.WebSearchTool#searchWeb` which is annotated with `@Tool`, but we don't create a bean for this class. 

As a first step, we should not consider this class a tool unless there is an implementation of `WebSearchEngine` (this isn't fool proof, but it's good enough for now)

**Comment by geoand** [comment]
I will fix this, but @jmartisk I think we need some sort of smoke test for the chat interface of the DevUI

**Comment by jmartisk** [comment]
@phillip-kruger are there any existing Dev UI tests that actually work with the UI?

**Comment by phillip-kruger** [comment]
There are tests for jsonrpc calls and tests for build time data. There are no Ui tests (as in playwright)
