### ISSUE TITLE
Expose metrics based on langchain4j model listener

### ISSUE THREAD

**Issue by cescoffier** [quarkiverse/quarkus-langchain4j#664]
Expose metrics based on https://github.com/langchain4j/langchain4j/pull/1229 to improve our observability support.

**Comment by geoand** [comment]
I am waiting for a release which will contain that new API.

**Comment by geoand** [comment]
😆

**Comment by geoand** [comment]
I have this ready. All we need to do now is wait for a LangChain4j release (which is imminent AFAIU)

**Comment by geoand** [comment]
https://github.com/quarkiverse/quarkus-langchain4j/pull/721
