### ISSUE TITLE
Exception when using a named datasource for pgvector

### ISSUE THREAD

**Issue by laurentperez** [quarkiverse/quarkus-langchain4j#667]
Hello

I'm getting a 

`2024-06-12 10:14:13.380 CEST+0200 (executor-thread-2 #137) (pid:1225493) io.quarkiverse.langchain4j.runtime.devui.ChatJsonRPCService:154 WARN java.util.concurrent.CompletionException: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [NcsXENBovnGlSJZ1aaFjoohrtKM]: java.lang.IllegalArgumentException: A synthetic injection point was not declared for required type [interface io.agroal.api.AgroalDataSource and qualifiers: [@jakarta.enterprise.inject.Default()] {} `

My database is configured as

```
quarkus.langchain4j.pgvector.dimension=1536
quarkus.datasource.hd.db-kind=postgresql
quarkus.datasource.hd.username=postgres
quarkus.datasource.hd.password=postgres
quarkus.datasource.hd.jdbc.url=jdbc:postgresql://localhost:5433/hd
quarkus.langchain4j.pgvector.datasource=hd
```

Are named datasources supported ? please note that if I make an explicit mistake and make a typo in "hd" (as in "hdfoo") it does not boot at all. "hd" boots, but this exception happens when I attempt the first call to the vector DS

thanks

**Comment by geoand** [comment]
cc @jmartisk
