### ISSUE TITLE
Show contents of memory in DevUI

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#691]
When playing around with the chat page in the DevUI, it would be nice if we could also display the contents of the chat memory

**Comment by jmartisk** [comment]
I'm not following, is that something else than the previous chat messages that stay on the page as you continue chatting?

**Comment by geoand** [comment]
Yeah, I would like to see the contents of the store itself because that way I can visualize how the eviction policy works

**Comment by jmartisk** [comment]
That is how it works currently, it sends back a full copy of the history every time, so AFAIU evicted messages should disappear. Well, at least without streaming mode. Streaming mode currently sends messages incrementally.

**Comment by geoand** [comment]
Gotcha, I'll have to look closer

**Comment by geoand** [comment]
Which screen do I see this in?

**Comment by geoand** [comment]
Nevermind, now I understand what you mean

**Comment by jmartisk** [comment]
@geoand can we close this then?

**Comment by geoand** [comment]
Sure yeah
