### ISSUE TITLE
How can I use multiple models of openai in the same application?

### ISSUE THREAD

**Issue by Camelxxl** [quarkiverse/quarkus-langchain4j#696]
I want to have one more simple approach with gpt 4o and one with 4, but I can't get it running.

I tried somethlink like:

```properties
quarkus.langchain4j.m1.chat-model.provider=openai
quarkus.langchain4j.openai.m1.chat-model.model-name=gpt-4o
quarkus.langchain4j.openai.m1.chat-model.temperature=0.5
quarkus.langchain4j.openai.m1.chat-model.max-tokens=2300
quarkus.langchain4j.openai.m1.timeout=60s
quarkus.langchain4j.openai.m1.log-requests=true
quarkus.langchain4j.openai.m1.log-responses=true

quarkus.langchain4j.m2.chat-model.provider=openai
quarkus.langchain4j.openai.m2.chat-model.model-name=gpt-4
quarkus.langchain4j.openai.m2.chat-model.temperature=0.5
quarkus.langchain4j.openai.m2.chat-model.max-tokens=2300
quarkus.langchain4j.openai.timeout=60s
quarkus.langchain4j.openai.log-requests=true
quarkus.langchain4j.openai.log-responses=true
```

but m2 is never working (yes I configured the api key)

I also tried to change the model via configuration changes at runtime, but its not working as well.

How can I accomplish that?

**Comment by geoand** [comment]
> but m2 is never working

What do you mean exactly? How are you using it?

**Comment by Camelxxl** [comment]
I am using it the same way I use m1 and get an error:

I have two services with
@RegisterAiService(modelName="m1")
@RegisterAiService(modelName="m2")
with exact same methods

the request post to openai log is printed and I get following error

2024-06-21 15:54:40,401 ERROR [io.qua.lan.run.ais.AiServiceMethodImplementationSupport] (ForkJoinPool.commonPool-worker-1) Execution method failed: java.lang.RuntimeException: jakarta.ws.rs.ProcessingException: The timeout period of 10000ms has been exceeded while executing POST /v1/chat/completions for server null

**Comment by geoand** [comment]
Can you please attach a sample application I can try next week?

**Comment by Camelxxl** [comment]
application.properties:
`
quarkus.langchain4j.openai.m1.api-key=sk-....
quarkus.langchain4j.openai.m2.api-key=sk-....

# Configure model 'm1' with GPT-4
quarkus.langchain4j.m1.chat-model.provider=openai
quarkus.langchain4j.openai.m1.chat-model.model-name=gpt-4o
quarkus.langchain4j.openai.m1.chat-model.temperature=0.5
quarkus.langchain4j.openai.m1.chat-model.max-tokens=2300
quarkus.langchain4j.openai.m1.timeout=60s
quarkus.langchain4j.openai.m1.log-requests=true
quarkus.langchain4j.openai.m1.log-responses=true

# Configure model 'm2' with GPT-4o
quarkus.langchain4j.m2.chat-model.provider=openai
quarkus.langchain4j.openai.m2.chat-model.model-name=gpt-4
quarkus.langchain4j.openai.m2.chat-model.temperature=0.5
quarkus.langchain4j.openai.m2.chat-model.max-tokens=2300
quarkus.langchain4j.openai.timeout=60s
quarkus.langchain4j.openai.log-requests=true
quarkus.langchain4j.openai.log-responses=true
`

`
@RegisterAiService(modelName="m1")
public interface AiServiceM1 {

    @SystemMessage("you are a chatbot")
    @UserMessage("""
        Data:
        {data}

    """)
    String createAnswer(String prompt);
}
`

`
@RegisterAiService(modelName="m2")
public interface AiServiceM2 {

    @SystemMessage("you are a chatbot")
    @UserMessage("""
        Data:
        {data}

    """)
    String createAnswer(String prompt);
}
`

and then just try to use  both, one will work the other not

**Comment by geoand** [comment]
Thanks, I'll give it a shot on Tuesday

**Comment by geoand** [comment]
I can't reproduce the problem.

**Comment by Camelxxl** [comment]
can you use both models without a problem?

**Comment by geoand** [comment]
Yes

**Comment by Camelxxl** [comment]
can you provide me your example that would be very helpful for me

**Comment by geoand** [comment]
I deleted it, but it essentially did what you are doing

**Comment by MarcScheib** [comment]
I had a similar problem and after a lot of debugging and testing different properties, my working solution was this (although it was working for me, I am not sure about the correctness):
- `quarkus.langchain4j.openai.timeout` working fine for only one unamed model, not working anymore at all with multiples
- `quarkus.langchain4j.timeout` always working
- `quarkus.langchain4j.openai.m1.timeout` working for indinvidual models

Deriving from this observations, the issue here is that your timeout for m2 is falling into the first bullet point, but as you are using multiple models, it is not applied. Therefore, you try using the overall timeout (which affects all models), or simply add the modelname (as in bullet point 3).
