### ISSUE TITLE
Allow the injection of TokenCountEstimator

### ISSUE THREAD

**Issue by andreadimaio** [quarkiverse/quarkus-langchain4j#697]
Today it is not possible to inject the `TokenCountEstimator`, this could be useful to estimate the number of tokens.

**Comment by geoand** [comment]
Where would one inject that?

**Comment by andreadimaio** [comment]
The idea is to have the same configuration of the `ChatLanguageModel`, in this case the developers can inject the interface where they prefer.

For example, suppose I have two AIServices configured with `watsonx`, one with `llama3` and the other with `mixstral`. The developer could inject the `TokenCountEstimator` for both models and choose which to use based on the token counts.

This is an idea of what I have in mind [LINK](https://github.com/quarkiverse/quarkus-langchain4j/commit/3efe0f0d14f3c4c79e5c27ea0692edbffe8a7f30).

**Comment by geoand** [comment]
We can certainly do that and it does makes sense!

**Comment by andreadimaio** [comment]
Ok, I'm going to share what I wrote (I have more tests to add) for the end of the day.

**Comment by geoand** [comment]
Thanks!
