### ISSUE TITLE
Nightly build against langchain4j main doesn't actually use the main branch

### ISSUE THREAD

**Issue by jmartisk** [quarkiverse/quarkus-langchain4j#701]
See https://github.com/quarkiverse/quarkus-langchain4j/blob/0.15.1/.github/workflows/build-against-langchain4j.yml#L45

We need to override the `langchain4j.version` property to the correct SNAPSHOT (and preferably also build the embeddings project and do the same with `langchain4j-embeddings.version`). Otherwise we're running against the version that we currently declare in the pom, which is not very useful to do nightly. The nightly job currently passes even though it should have started failing weeks ago due to https://github.com/langchain4j/langchain4j/pull/1226/ 

Or maybe it would be better to turn things around and introduce a CI build in langchain4j that runs the quarkus-langchain4j build for every PR in langchain4j? I briefly asked @langchain4j and he seems fine with it. WDYT @geoand? It would force langchain4j to be a bit more conservative, hopefully ;) (or at least let us know right away when something breaks)

**Comment by geoand** [comment]
>  It would force langchain4j to be a bit more conservative, hopefully

That is actually the exact opposite of what I want 😎.
I want upstream to do whatever is best for the project and the community and for us to adapt as necessary

**Comment by jmartisk** [comment]
I see :) ok then, in that case I guess I'll just try to fix the nightly job

**Comment by geoand** [comment]
🙏

**Comment by langchain4j** [comment]
> It would force langchain4j to be a bit more conservative

It would not harm to at least _be aware_ if I accidentally break anything

**Comment by geoand** [comment]
Sure yeah, that makes sense

**Comment by jmartisk** [comment]
I've submitted https://github.com/quarkiverse/quarkus-langchain4j/issues/701 to fix the nightly job on our side.

@langchain4j We can still have the tests in the langchain4j project too (but it may be too heavyweight), or maybe we could somehow make the nightly job send you notifications, or something?!

**Comment by langchain4j** [comment]
@jmartisk if notifications can be done, then it would probably be the easiest way?

**Comment by jmartisk** [comment]
Would this work? https://github.com/marketplace/actions/send-workflow-notifications

**Comment by langchain4j** [comment]
@jmartisk seems like yes, let's try it?
