### ISSUE TITLE
Ollama version > 0.2.5 : Role should be sent in lowercase

### ISSUE THREAD

**Issue by humcqc** [quarkiverse/quarkus-langchain4j#743]
After upgrading to Ollama 0.2.5, the application start failing.
Ollama change the the role case. A fix is in progress: https://github.com/ollama/ollama/issues/5687

But Ollama recommend to send role in lowercase now.

**Comment by geoand** [comment]
Thanks for reporting!

Do you want to fix this?

**Comment by humcqc** [comment]
> Thanks for reporting!
> 
> Do you want to fix this?

Why not!
should we force to be compatible with ollama > 0.2.5 ? Or we should do something depending on Ollama Server version ?

**Comment by geoand** [comment]
> Why not!

Thanks!

> should we force to be compatible with ollama > 0.2.5

Defnitely not :). Can't we always send it lowercase?

**Comment by humcqc** [comment]
> Defnitely not :). Can't we always send it lowercase?

Not sure, I will check in ollama previous code.
