### ISSUE TITLE
[Question] How to dynamic filter metadata besides chat memory id

### ISSUE THREAD

**Issue by cmasantos** [quarkiverse/quarkus-langchain4j#760]
Hi, I'm not sure if this is the right place to ask this question but here it goes. 

I was trying to understand how could I filter the documents in PgVector based on the metadata, for example if i'm searching books, I'd like to filter by the metadata key `authorName`. 

Looking at this PR https://github.com/quarkiverse/quarkus-langchain4j/pull/619 I know it possible but at an higher level I can't understand how could I make a parameter go from the rest endpoint to the query in the content retriever.

In this example ([AiWithUserFilterService.java](https://github.com/humcqc/quarkus-langchain4j/blob/8372d80b2134a66f1519e7db802c3d79f3cdb21e/integration-tests/rag-pgvector-flyway/src/main/java/org/acme/example/AiWithUserFilterService.java#L45)) we can see how a dynamic filter works but only for `query.metadata().chatMemoryId()` since the `dev.langchain4j.rag.query.Metada.java` ([here](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-core/src/main/java/dev/langchain4j/rag/query/Metadata.java)) from the [query](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-core/src/main/java/dev/langchain4j/rag/query/Query.java) contains only 3 fields  and it's not the same Metadata class used on the documents ingestion (`dev.langchain4j.data.document.Metadata`).

Is this possible or do I need to go the "low level" side of langchain4j?

Thank you

**Comment by geoand** [comment]
AFAIK, the only way to "pass" information is to use a `@MemoryId`  parameter. But that does seem pretty limiting to be honest. 

@langchain4j is there another way I've missed to provide "data" for metadata filtering?

**Comment by geoand** [comment]
@humcqc it seems like we would need to update our `PgVectorEmbeddingStore` implementation to have parity with the one from upstream LangChain4j. Would you like to do that?

**Comment by langchain4j** [comment]
Hi, right now only memory id can be passed through "AI services", there is an [issue](https://github.com/langchain4j/langchain4j/issues/1122) to allow other custom parameters.

Before this is implemented, you could either 1. do it on a lower level or 2. temporarily associate filter with the memory id before invoking ai service and then resolve it (which is dirty but will work)

**Comment by geoand** [comment]
Thanks a lot @langchain4j !

**Comment by cmasantos** [comment]
Thank you for the responses 👍

**Comment by humcqc** [comment]
Hello,

Yes for the moment i use MemoryId to pass all my needed data and filter.
It s not ideal but it works. Perhaps we can add an example of it.

Then I think we need to add a kind of QueryContext where we can add
whatever context we need.

In my case i need user authentication context, tenant, and some user data
to be able to use the tools , fikters, transformers, routers correctly.

This context should be pass to the tools and to the transformers and
routers too.

For me nothing to change in the pgvectorembedingstore. All seems available
to filter when the context or new parameters will be available.

Le lun. 22 juil. 2024, 10:05, LangChain4j ***@***.***> a
écrit :
