### ISSUE TITLE
Multi<String> and spaces - stripped responses

### ISSUE THREAD

**Issue by kucharzyk** [quarkiverse/quarkus-langchain4j#761]
I am observing some weird behavior with Quarkus, langchain4j and Ollama.

My  AI service is returning `Multi<String>` and I am streaming response through websocket.

When I ask about something where numbers are involved like `How much is 2+2?` my responses looks like this:

```
'2'
' +'
'2'
' ='
'4'
'Let'
' me'
' know'
' if'
' you'
' have'
' any'
' other'
' math'
' problems'
' you'
'''
'd'
' like'
' to'
' solve'
'!'
' 😄'
```

```2 +2 =4Let me know if you have any other math problems you'd like to solve! 😄```

There is always missing space somewhere around the numbers.

When my response type is just a `String` responses looks correct like: ` 2 + 2 = 4`

It might be a bug.

**Comment by kucharzyk** [comment]
Update: It looks like it's not the problem with numbers.

If I use prompt "Output A, 11 spaces and B" I am getting "A           B"

But using `Multi<String>` only
```
'A'
'B'
```

I've checked codebase and in few places there is a code like:

```java
// Skip empty responses from LLM.
if (response == null || response.isBlank())
    return;
```
It looks it ignores all the spaces send from LLM

**Comment by kucharzyk** [comment]
I think the same @andreadimaio but I am wondering why this check was added.

@geoand - Do you remember why why are skipping blank responses?

**Comment by andreadimaio** [comment]
For other LLM providers, like watsonx, the `isBlank` is mandatory because the API returns a JSON object to parse.

Ollama seems to always return a string, so the `isBlank` could be removed or replaced with a `isEmpty,` but maybe there is something I am ignoring.

**Comment by geoand** [comment]
> @geoand - Do you remember why why are skipping blank responses?

Unfortunately I do not. It is probably a bug and `isEmpty` should be used. Would you like to try that?

**Comment by kucharzyk** [comment]
I can try to create PR this evening.
