### ISSUE TITLE
Improve JSON sanitize

### ISSUE THREAD

**Issue by andreadimaio** [quarkiverse/quarkus-langchain4j#776]
The [sanitize method](https://github.com/quarkiverse/quarkus-langchain4j/blob/b52c8414bc61640347b47d93283d8f084f2148bc/core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusJsonCodecFactory.java#L34-L35) doesn't work if the LLM returns as ouput:

Example 1:
```
```\n{ ... }\n```
```
Example 2:
```
```json\n{ ... }\n
```
Example 3:
```
```\n{ ... }\n
```

The second and third examples can occur when a developer uses the `chat-model.stop-sequences=}\n` property.
One solution might be to use the regex: **```(json)***

**Comment by geoand** [comment]
Would you like to work on an improvement?

**Comment by andreadimaio** [comment]
The regex `"(\\\\n)*```(json)?(\\\\n)*"` solve the problem. Let me create a PR.
