### ISSUE TITLE
chatMemoryProviderSupplier on AiService doesn't get picked up

### ISSUE THREAD

**Issue by schoeffm** [quarkiverse/quarkus-langchain4j#782]
I was following the [documentation](https://docs.quarkiverse.io/quarkus-langchain4j/dev/ai-services.html#_advanced_usage) and was trying to define my own `chatMemoryProviderSupplier`. When I start a new chat by using the dev-tools UI my `CustomProvider` doesn't get called at all.

(short side note: `@RegisterAiService(chatMemoryProviderSupplier = MySmallMemoryProvider.class)` in the docs seems also wrong and should be `@RegisterAiService(chatMemoryProviderSupplier = CustomProvider.class)` instead, I guess).

So, I tried to provide a vanilla project that focuses just on that issue (I am using ollama - zip-archive attached). So, this is the service:

```java
@SessionScoped
@RegisterAiService(chatMemoryProviderSupplier = CustomProvider.class)
public interface MyAiService {

    @SystemMessage("You are a professional poet")
    String chat(@MemoryId int memoryId, @UserMessage String userMessage);
}
```

While this is the `CustomProvider` I'm referencing (this one throws an exception on purpose to emphasize the point).
```java
public class CustomProvider implements Supplier<ChatMemoryProvider> {
    @Override
    public ChatMemoryProvider get() {
        throw new UnsupportedOperationException("This is not called!!");
    }
}
```
The program runs just fine without any exception - the Supplier isn't called. Do I have to do sth. else in order to register it?

Example-Project: [qarkus-langchain4j-chatmemory.zip](https://github.com/user-attachments/files/16380381/qarkus-langchain4j-chatmemory.zip)

**Comment by geoand** [comment]
Thanks for reporting.

If I add:

```java

@Path("test")
public class TestResource {

    private final MyAiService myAiService;

    public TestResource(MyAiService myAiService) {
        this.myAiService = myAiService;
    }

    @GET
    public String chat() {
        return myAiService.chat(1, "what is your name?");
    }
}

```

so the service actually gets invoked, I do see the desired exception:

```
jakarta.enterprise.inject.CreationException: Error creating synthetic bean [ajJXFdeYupxDGBnNL-lgJs343NM]: java.lang.UnsupportedOperationException: This is not called!!
```

Am I missing something?

**Comment by schoeffm** [comment]
Indeed - my bad - I thought that also the Dev UI Chat would use and instanciate my `AiService`-class - but I guess I have to use "my" instance explicitly to get it instantiated.
Thx!

**Comment by geoand** [comment]
🙏🏼
