### ISSUE TITLE
Add observability

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#8]
Also, take a look at https://smith.langchain.com/

**Comment by geoand** [comment]
@cescoffier what do you have in mind for the audit service?

**Comment by cescoffier** [comment]
@geoand 

The audit service would be an optional interface that the user can implement to store the interactions with the LLMs. It's like the `access.log` but for LLM - and the format should be defined by the users (as there is a good chance it needs to go in a DB).

Basically, the interface will do something like:

```java
Audit initAudit(String systemMessage, String userMessage)
```

with Audit the object on which we can report the additional messages and RAG:

```
Audit addLLMToApplicationMessage(...)
Audit addApplicationToLLMMessage(...)
Audit addRelevantDocument(...)
void onCompletion(); // Complete the audit -> persist it, log it
void onFailure(Throwable t); // The LLM interaction failed
```

Each recorded _step_ should have the message direction (LLM -> App or App -> LLM) and the timestamp.  

**Unknowns**:

- Should audi be part of the same transaction as the LLM interaction - I would say yes.  But it's rather convoluted to force that behavior in a first step.

**Comment by geoand** [comment]
Closing as we already have this
