### ISSUE TITLE
Investigate providing a seeded chat memory

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#800]
One way of providing few shot prompts to an LLM is by seeing the conversation with memory - see https://glaforge.dev/posts/2024/07/30/sentiment-analysis-with-few-shots-prompting/ as an example. 

We could do something like this:

```java
@RegisterAiService
interface SentimentAnalysis {
    @SystemMessage("""
        Analyze the sentiment of the text below.
        Respond only with one word to describe the sentiment.
        """)
    Sentiment analyze(String text);

    @SeedMemory
    static List<ChatMessage> memory() {
       return List.of(UserMessage.from("This is fantastic news!"), AiMessage.from(Sentiment.POSITIVE.name()))
    }
}
``` 

The idea for the API used here is taken from what we do in the REST Client for exception mappers.

**Comment by geoand** [comment]
@jmartisk WDYT?

**Comment by gastaldi** [comment]
Would it make sense to return a `Multi<ChatMessage>` or `Stream<ChatMessage>`? That would be useful for producing on demand 😀

**Comment by geoand** [comment]
I don't think it will be needed at first, but it can't be ruled out in the future if more advanced use cases arise

**Comment by andreadimaio** [comment]
I think this is something that can help a lot, especially if there is a need to add tags related to the LLM. In my specific case, this saves me from having to include all the few-shots with the relative tags in the `@SystemMessage`

**Comment by geoand** [comment]
#804 brings in this functionality
