### ISSUE TITLE
@SystemMessage(fromResource = "bad-path.txt") fails with `@SystemMessage's template parameter cannot be empty`

### ISSUE THREAD

**Issue by dastrobu** [quarkiverse/quarkus-langchain4j#831]
If an AI service is condfigured with a bad path it fails with: `@SystemMessage's template parameter cannot be empty`

```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.langchain4j.deployment.AiServicesProcessor#handleAiServices threw an exception: dev.langchain4j.exception.IllegalConfigurationException: @SystemMessage's template parameter cannot be empty. Offending method is 'io.quarkiverse.langchain4j.openai.test.ServiceWithResource#findTalks'
	at dev.langchain4j.exception.IllegalConfigurationException.illegalConfiguration(IllegalConfigurationException.java:12)
```

It should fail with something like "resource not found". 

Relevant code is: https://github.com/quarkiverse/quarkus-langchain4j/blob/323966c4d3f155bda7d57e9d824f512517a01e5c/core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java#L1127

Probably there should be an else case on reading the `is` like: 

```java
                if (is != null) {
                    return new String(is.readAllBytes());
                }else {
                    throw new FileNotFoundException("Resource not found: " + fromResource);
                }
```

**Comment by geoand** [comment]
That makes sense! Would you like to contribute such a fix?

**Comment by dastrobu** [comment]
@geoand see https://github.com/quarkiverse/quarkus-langchain4j/pull/834
