### ISSUE TITLE
Make sure we follow OTEL observability recommendations

### ISSUE THREAD

**Issue by cescoffier** [quarkiverse/quarkus-langchain4j#849]
We may not be limited to these recommendations, but providing them should be ensured:

See:
https://opentelemetry.io/blog/2024/llm-observability/

**Comment by geoand** [comment]
We are already doing that :)

**Comment by cescoffier** [comment]
All of them?

**Comment by geoand** [comment]
> Do we have top_p/k, temperature in our span on the request and response?

[Yup](https://github.com/quarkiverse/quarkus-langchain4j/blob/0.17.2/core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/listeners/SpanChatModelListener.java)

> The cost part seems missing (not sure how we could compute it actually

Right, I have no idea how we can add those
