### ISSUE TITLE
Is it a good idea to have Testcontainers in the classpath just for Dev UI?

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-langchain4j#854]
I was developing an application with this extension and when using Jackson, Testcontainers imports kept being in the way because they are shading Jackson.

I was wondering why Testcontainers was around as I was in the runtime classpath and this is because we import `quarkus-devservices-common` in the core for `OpenWebUIJsonRPCService`.

I'm not entirely sure it's a good idea to have Testcontainers around in the runtime. The dev experience is not exactly ideal out of the box when you try to import Jackson classes.
And you end up with quite a bunch of classes you will never use at runtime (except in dev mode).

I'm not exactly sure how we can solve this problem though. Basically, we have:

- Deployment dependencies
- Runtime dependencies
- Dependencies that somehow need to be visible to the runtime but only in dev mode

I'm starting to wonder if we should isolate the Dev UI components in a separate artifact as they are a weird beast.

/cc @aloubyansky @phillip-kruger as it goes beyond Quarkus LangChain4j.

**Comment by phillip-kruger** [comment]
OpenWebUIJsonRPCService should not be doing that. There is a way an extension can execute against the deployment classpath (even for JsonRPC calls) - see https://quarkus.io/guides/dev-ui#jsonrpc-against-the-deployment-classpath

This way nothing is pulled into the runtime classpath

**Comment by geoand** [comment]
@phillip-kruger any chance you can provide a quick fix?

**Comment by phillip-kruger** [comment]
I'll have a look

**Comment by geoand** [comment]
🙏
