### ISSUE TITLE
Support jlama

### ISSUE THREAD

**Issue by jesuino** [quarkiverse/quarkus-langchain4j#870]
Opening this for keep track of JLama support. It has already integration with langchain4j, hence I think we could support with Quarkus.

With JLama I think we would finally have a self-contained Quarkus app. In another words, we could have the Quarkus final package (binary or JAR) that would not require external dependencies (ollama, etc) because it would include the open source model and the java code to run inference on it!

https://github.com/langchain4j/langchain4j-examples/tree/main/jlama-examples

**Comment by geoand** [comment]
We absolutely can have this!

One thing that won't work currently (AFAIK) is building to a native image

**Comment by jesuino** [comment]
I see that it is a working progress in jLama, it is on their [roadmap](https://github.com/tjake/Jlama?tab=readme-ov-file#%EF%B8%8F-roadmap)!  I wonder if GraalVM supports the new Vector API.

**Comment by geoand** [comment]
Last time I checked, it did not

**Comment by geoand** [comment]
@jesuino would you like to contribute this feature?

It should be fairly straightforward to add if you follow what the code does for Mistral for example

**Comment by jesuino** [comment]
@geoand I will try and let you know. I need it in my project as well.

Thanks

**Comment by geoand** [comment]
Cool, thanks!

Due let us know if you need help
