### ISSUE TITLE
Redis embedding store does not work anymore

### ISSUE THREAD

**Issue by cescoffier** [quarkiverse/quarkus-langchain4j#896]
The error is:

```
{"code":-32603,"message":"Method [io.quarkiverse.langchain4j.quarkus-langchain4j-core.findRelevant] failed: Syntax error at offset 1 near >["}
```

```
The passed query is `*=>[ KNN 10 @vector $BLOB AS vector_score ]`
```

The ingestor is just:

```
    public void ingest(@Observes StartupEvent ev,
                       RedisDataSource redis,
                       RedisEmbeddingStore store, BgeSmallEnQuantizedEmbeddingModel embeddingModel,
                       @ConfigProperty(name = "rag.location") Path documents) {
        redis.flushall(); // cleanup the Redis to start fresh (for demo purpose only)
        List<Document> list = FileSystemDocumentLoader.loadDocumentsRecursively(documents);
        EmbeddingStoreIngestor ingestor = EmbeddingStoreIngestor.builder()
                .embeddingStore(store)
                .embeddingModel(embeddingModel)
                .documentSplitter(recursive(100, 25))
                .build();
        ingestor.ingest(list);
        Log.info("Documents ingested successfully");
    }
```

wondering is the syntax should not be (*)=>

**Comment by geoand** [comment]
cc @jmartisk

**Comment by jmartisk** [comment]
`*=>` and `(*)=>` should be equivalent, that is the metadata filter, and we send `*` when there's no filter in use

I tried and couldn't reproduce it (I'm using the `chatbot` sample, which has pretty much the same code as you pasted in the description, and with `redis/redis-stack:latest` image)

**Comment by jmartisk** [comment]
So most likely it sounds to me like an incompatible Redis version?!

**Comment by cescoffier** [comment]
@jmartisk Can you check the sha of your Redis stack image. Here is mine:
docker.io/redis/redis-stack                                                                         latest               ce0b378f9900  7 weeks ago    748 MB

**Comment by cescoffier** [comment]
@jmartisk Sorry, forgot to post the application I'm using. 
It's https://github.com/cescoffier/quarkus-langchain4j-workshop/tree/main/step-06. 

Just replace the PGVector one with the Redis one.

**Comment by jmartisk** [comment]
Looking at it - your app starts working for me when I switch it to Quarkus 3.12.1 instead of 3.14.4. So I think the difference is something that has changed in the Redis client extension on the Quarkus side.

**Comment by jmartisk** [comment]
I can probably fix that, but we might wanna consider adding some sort of CI against a matrix of supported Quarkus versions. AFAIK we only have something with the latest Quarkus snapshot and it is broken now. That's how we missed that Quarkus 3.13 breaks this embedding store.

**Comment by jmartisk** [comment]
We're in a bit of a pickle, because changing to `.dialect(2)` doesn't work on Quarkus < 3.13. We would have to detect the running Quarkus version and decide what to do based on that....
The other option is to just deal with it that right now it will not work on 3.13+, but when we upgrade to 3.15, we make the fix along with that.

**Comment by geoand** [comment]
I would much rather have a temporary fix for now (Quarkus LangChain4j 0.18) and then remove it for `0.19`

**Comment by jmartisk** [comment]
Ok but to have a temporary fix that works on all Quarkus versions from 3.8 to 3.14, we will have to detect the Quarkus version and choose which method to call based on that, is that doable?

**Comment by geoand** [comment]
Detecting the version is easy :). 

As for the which method to call, what exactly are you referring to?

**Comment by jmartisk** [comment]
Any example where else we do this?

https://github.com/quarkiverse/quarkus-langchain4j/blob/0.18.0.CR1/embedding-stores/redis/runtime/src/main/java/io/quarkiverse/langchain4j/redis/RedisEmbeddingStore.java#L177

here we need to call `.param("DIALECT", "2")` on Quarkus <= 3.12 and replace with `.dialect(2)` on Quarkus >= 3.13

**Comment by geoand** [comment]
Oh, okay :). 

`io.quarkus.builder.Version.getVersion()` will give you the Quarkus version in a Quarkus build step. 
As the bean is synthetic, you can just pass that version to the recorder and use it at will
