### ISSUE TITLE
Enable configuration of AI service method parameters ignored annotations

### ISSUE THREAD

**Issue by aldettinger** [quarkiverse/quarkus-langchain4j#902]
In the same spirit of #888, it would be a nice addition to implement a predicate based build item to handle ignored annotations. This idea was discussed in this [context](https://github.com/quarkiverse/quarkus-langchain4j/pull/889#discussion_r1762995150).

**Comment by geoand** [comment]
👍🏽

**Comment by aldettinger** [comment]
I should be able to work on this in the coming day, feel free to assign to me if it make sense.

**Comment by geoand** [comment]
🙏
