### ISSUE TITLE
Watsonx not found in Quarkus Tools for vscode

### ISSUE THREAD

**Issue by andreadimaio** [quarkiverse/quarkus-langchain4j#916]
I'm using vscode and when I search for the Langchain4j extension in Quarkus (using Quarkus Tools) I don't find watsonx in the list.

**Comment by geoand** [comment]
I am pretty sure you need to add the extension metadata to https://github.com/quarkusio/quarkus-extension-catalog/tree/main/extensions (in the same way the others are added)

**Comment by andreadimaio** [comment]
quarkusio/quarkus-extension-catalog#113

**Comment by geoand** [comment]
Merged, thanks!

I don't remember how often the registry is checked, but it should be available pretty soon
