### ISSUE TITLE
Suggestion: Reduce repetition of words in Guardrails API signature?

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-langchain4j#926]
I notice that

```
public interface InputGuardrail extends Guardrail<InputGuardrail.InputGuardrailParams, InputGuardrailResult> {
```

repeats `InputGuardrail` four times in the one line. 

Instead, could we have 

```
public interface InputGuardrail extends Guardrail<InputGuardrailParams, InputGuardrailResult> {
```
(no inner class)

or 

```
public interface InputGuardrail extends Guardrail<InputGuardrail.Params, InputGuardrailResult> {
```

(inner class, but without the repeated `InputGuardrail`?)

Similarly, 

```
public interface OutputGuardrail extends Guardrail<OutputGuardrail.OutputGuardrailParams, OutputGuardrailResult> {
```

could be 

```
public interface OutputGuardrail extends Guardrail<OutputGuardrailParams, OutputGuardrailResult> {
```

or 

```
public interface OutputGuardrail extends Guardrail<OutputGuardrail.Params, OutputGuardrailResult> {
```

The option without the inner class is perhaps better, since otherwise there's a puzzling asymmetry (why is the `Params` an inner class, but `OutputGuardrailResult` gets its own top-level class?)

**Comment by holly-cummins** [comment]
(I can do a PR, but won't until we discuss whether there's a reason for the current style.)

**Comment by geoand** [comment]
+1 from me, but it's up to @cescoffier

**Comment by cescoffier** [comment]
No problem for me, @mariofusco you ok with it?

**Comment by mariofusco** [comment]
This is also ok for me. Thanks for giving a look at it @holly-cummins, let me know if I can help.
