### ISSUE TITLE
[FEATURE] Select tools dynamically on incoming message

### ISSUE THREAD

**Issue by MiggiV2** [quarkiverse/quarkus-langchain4j#962]
I've already worked on an analogous feature within the [langchain4j/langchain4j](https://github.com/langchain4j/langchain4j) project, where I implemented [dynamic tool registration](https://github.com/langchain4j/langchain4j/pull/1644) for LangChain. Now, I want to extend this functionality to the **quarkus-langchain4j** extension.

### **Describe the solution you'd like**

The goal is to enable **dynamic tool registration** at runtime to allow for more flexible and scalable tool integration. Instead of declaring tools upfront in a static way, we propose allowing Quarkus LangChain4j users to **register tools dynamically** and **distribute them effectively**.

#### Code Example

```java
@RegisterAiService(toolProvider = MyCustomToolProvider.class)
public interface Bot {

    @SystemMessage("You are an AI named Bob answering questions about financial products.")
    String chat(@UserMessage String question);
}
```

In this example:

- The `Bot` interface is registered with the `AIService`, while the actual tools are injected at runtime using `MyCustomToolProvider.class`.
- This allows for dynamic selection and attachment of tools based on runtime conditions, granting flexibility over tool management and usage.
- Compiling with a locked set of tools is no longer needed, making the bot easier to customize per environment or customer.

---

### **Proposal and Commitment**

We at **EXP** would be happy to contribute a pull request for this feature. I plan to share an initial implementation soon and welcome any feedback or further ideas from the community before delving deeper into the work.

Thank you very much for considering this feature request! Looking forward to engaging with everyone on this.

**Comment by geoand** [comment]
Thanks a lot for reporting!

I like the idea, feel free to open a Pull Request so we can discuss further.

cc @cescoffier @andreadimaio

**Comment by andreadimaio** [comment]
If I understand correctly, the idea is to start from a list of tools that can be large and send to the LLM only the list that matches the user's request. 

For example, suppose I have a class that exposes two tools, one to perform a `sum` and another to perform a `web search`.
If the user's query is: **"Execute the sum of 1 + 1"**, the prompt of the LLM will contain only the first tool. 

This allows to streamline the prompt and to avoid hallucinations.
Is this correct?

**Comment by cescoffier** [comment]
But how would you select the tools  for a specific call?

**Comment by andreadimaio** [comment]
> But how would you select the tools for a specific call?

Good question... embedding? In any case, it should be something that can be customised to use the best approach, but yes, the doubt remains.

**Comment by cescoffier** [comment]
That what I was thinking too.

**Comment by MiggiV2** [comment]
Thank you all for your feedback and the great ideas :)
The behavior for the [ToolProvider](https://github.com/langchain4j/langchain4j/blob/main/langchain4j/src/main/java/dev/langchain4j/service/tool/ToolProvider.java) is already defined and implemented upstream in LangChain4J.
The only idea of this issue this, to make this feature available in Quarkus.
