### ISSUE TITLE
Allow configuring the tls-configuration-name for the Model providers using the REST client

### ISSUE THREAD

**Issue by cescoffier** [quarkiverse/quarkus-langchain4j#993]
We have a case where the remote model provider uses a self-signed certificate (yes, yes, I know.... 2024). It would be great to have the possibility to configure the `tls-configuration-name` and allow the loading of the TLS configuration for the Quarkus TLS registry. 

I mentioned in the title model providers, but anything remote should offer that possibility.

**Comment by geoand** [comment]
Interesting. We can certainly do this

**Comment by geoand** [comment]
@cescoffier I assume https://github.com/quarkiverse/quarkus-langchain4j/pull/1006 is what you are after?

**Comment by cescoffier** [comment]
yes, exactly. 

We have a case where we need to connect to a model server using self-signed certificates.

**Comment by geoand** [comment]
👍🏽

**Comment by geoand** [comment]
You'll love the hack I had to come up with the make OpenAI work... 
It still needs more work, so I'll finish the PR tomorrow.

**Comment by geoand** [comment]
PR is now ready to go
