### ISSUE TITLE
Management Trust Certificate 

### ISSUE THREAD

**Issue by johneldyerelbey** [quarkiverse/quarkus-langchain4j#996]
https://github.com/quarkiverse/quarkus-langchain4j/blob/fa11843bba5aa1ead0b3fb504bfb4b24eee53902/model-providers/openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/common/OpenAiRestApi.java#L427

**Comment by geoand** [comment]
Can you please provide more information about what the issue is?

**Comment by geoand** [comment]
Closing for lack of feedback

**Comment by geoand** [comment]
Can you please elaborate on how this relates to the project?

Thanks
